// AUTO-GENERATED by scripts/blodia_levels.py - edit the paths there, then run:
//   python3 scripts/blodia_levels.py
// Board shapes of the first 20 Blodia levels (layout only, PYRODIA graphics).
import type { LevelDef } from '../LevelDef';

export const BLODIA_LEVELS: LevelDef[] = [
  {
    "id": 1,
    "name": "Twin Loops",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 6,
      "y": 2,
      "from": "S"
    },
    "countdown": 30,
    "flameSpeed": 0.9,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 550,
    "fuelPerTile": 0,
    "rows": [
      "-- -- -- -- -- -- -- -- -- -- -- -- -- --",
      "-- -- -- -- -- -- -- -- -- -- -- -- -- --",
      "-- -- -- C1 I1 I1 C2 C1 I1 I1 C2 -- -- --",
      "-- -- -- I0 -- -- -- I0 -- -- I0 -- -- --",
      "-- -- -- I0 -- -- .. I0 -- -- I0 -- -- --",
      "-- -- -- C0 I1 I1 C3 C0 I1 I1 C3 -- -- --",
      "-- -- -- -- -- -- -- -- -- -- -- -- -- --",
      "-- -- -- -- -- -- -- -- -- -- -- -- -- --"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ],
    "hint": "Blodia rules: the flame must travel through EVERY pipe. Slide tiles into the black hole, even the one carrying the flame. TURBO starts early."
  },
  {
    "id": 2,
    "name": "Rails",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 2,
      "y": 3,
      "from": "W"
    },
    "countdown": 30,
    "flameSpeed": 0.9,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 600,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "I1 C2 I1 I1 I1 I1 I1 I1 I1 I1 I1 I1 -- I1",
      "C2 C0 I1 I1 I1 I1 I1 I1 I1 I1 I1 I1 .. I1",
      "C0 I1 I1 I1 I1 I1 I1 I1 I1 I1 -- I1 I1 I1",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ],
    "hint": "A pipe that leaves one edge comes back on the opposite edge."
  },
  {
    "id": 3,
    "name": "Brackets",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 6,
      "y": 1,
      "from": "N"
    },
    "countdown": 80,
    "flameSpeed": 0.9,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 650,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## C1 I1 C2 C1 I1 C2 ## ## ## ##",
      "## ## ## ## I0 C1 C3 C0 C2 I0 ## ## ## ##",
      "## ## ## ## I0 I0 ## ## I0 I0 ## ## ## ##",
      "## ## ## ## I0 I0 ## ## I0 I0 ## ## ## ##",
      "## ## ## ## I0 I0 ## ## I0 I0 ## ## ## ##",
      "## ## ## ## I0 I0 ## ## I0 I0 ## ## ## ##",
      "## ## ## ## I0 C0 C2 C1 C3 I0 ## ## ## ##",
      "## ## ## ## C0 I1 C3 C0 .. C3 ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ],
    "hint": "Travelled pipes glow orange; the counter shows how many are left."
  },
  {
    "id": 4,
    "name": "Diamond Weave",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 5,
      "y": 1,
      "from": "W"
    },
    "countdown": 30,
    "flameSpeed": 0.9,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 700,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## I0 ## ## ## ## ## ## ##",
      "## ## ## ## ## I1 Z1 C2 ## ## ## ## ## ##",
      "## ## ## C1 I1 X0 I1 Z0 I1 C2 ## ## ## ##",
      "## C1 I1 Z1 I1 Z1 I1 X0 I1 Z0 I1 C2 ## ##",
      "## C0 I1 Z0 I1 X0 I1 X0 I1 Z1 I1 C3 ## ##",
      "## ## ## C0 I1 .. C2 I0 I1 C3 ## ## ## ##",
      "## ## ## ## ## C0 X0 C3 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 5,
    "name": "Pyramid",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 2,
      "y": 6,
      "from": "E"
    },
    "countdown": 30,
    "flameSpeed": 0.9,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 750,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## C1 C2 ## ## ## ## ## ##",
      "## ## ## ## ## C1 Z1 .. C2 ## ## ## ## ##",
      "## ## ## ## C1 Z1 Z0 Z0 Z0 C2 ## ## ## ##",
      "## ## ## C1 C3 C0 Z1 Z0 Z0 Z0 C2 ## ## ##",
      "## ## C1 Z1 I1 I1 X0 C3 C0 C3 C0 C2 ## ##",
      "## ## C0 C0 I1 I1 C0 I1 I1 I1 I1 C3 ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 6,
    "name": "Hook",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 7,
      "y": 3,
      "from": "N"
    },
    "countdown": 30,
    "flameSpeed": 1.0,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 800,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## -- -- -- -- -- -- -- -- ## ## ##",
      "## ## ## -- -- -- -- C1 ## ## -- ## ## ##",
      "## ## ## -- -- -- -- I0 ## ## -- ## ## ##",
      "## ## ## C1 I1 I1 I1 X0 I1 C3 -- ## ## ##",
      "## ## ## I0 -- -- -- I0 -- -- -- ## ## ##",
      "## ## ## I0 -- -- -- I0 -- -- -- ## ## ##",
      "## ## ## I0 .. -- -- I0 -- -- -- ## ## ##",
      "## ## ## C0 I1 I1 I1 C3 -- -- -- ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 7,
    "name": "Lattice",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 3,
      "y": 2,
      "from": "W"
    },
    "countdown": 20,
    "flameSpeed": 1.0,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 850,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## C1 X0 I1 X0 I1 X0 I1 C2 ## ## ##",
      "## ## ## Z1 X0 C2 I0 C1 X0 C2 I0 ## ## ##",
      "## ## ## I0 I0 C0 X0 C3 I0 I0 I0 ## ## ##",
      "## ## ## I0 I0 C1 X0 C2 I0 I0 I0 ## ## ##",
      "## ## ## I0 C0 C3 I0 C0 X0 C3 I0 ## ## ##",
      "## ## ## C0 I1 I1 .. I1 X0 I1 C3 ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia",
      "approximation"
    ]
  },
  {
    "id": 8,
    "name": "Open Square",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 9,
      "y": 1,
      "from": "W"
    },
    "countdown": 30,
    "flameSpeed": 1.0,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 900,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## C1 .. I1 I1 I1 C2 ## ## ## ##",
      "## ## ## ## I0 ## ## ## ## I0 ## ## ## ##",
      "## ## ## ## I0 ## ## ## ## I0 ## ## ## ##",
      "## ## ## ## I0 ## ## ## ## I0 ## ## ## ##",
      "## ## ## ## I0 -- -- -- -- I0 ## ## ## ##",
      "## ## ## ## C0 I1 I1 I1 -- C3 ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 9,
    "name": "Broken Frame",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 5,
      "y": 1,
      "from": "W"
    },
    "countdown": 30,
    "flameSpeed": 1.0,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 950,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## C1 I1 I1 I1 -- C2 ## ## ## ##",
      "## ## ## ## I0 .. -- -- I1 I0 ## ## ## ##",
      "## ## ## ## I0 -- -- -- -- I0 ## ## ## ##",
      "## ## ## ## -- I0 -- -- -- I0 ## ## ## ##",
      "## ## ## ## -- C0 I1 -- I0 I0 ## ## ## ##",
      "## ## ## ## -- -- -- I1 I1 C3 ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 10,
    "name": "Snake",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 9,
      "y": 2,
      "from": "W"
    },
    "countdown": 40,
    "flameSpeed": 1.0,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1000,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## C0 Z0 C2 C1 C2 C2 ## ## ## ##",
      "## ## ## ## C1 Z1 Z1 Z0 Z1 C3 ## ## ## ##",
      "## ## ## ## Z0 X0 Z1 Z0 Z0 C2 ## ## ## ##",
      "## ## ## ## C0 Z0 .. C3 C0 C3 ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia",
      "approximation"
    ]
  },
  {
    "id": 11,
    "name": "Steps",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 0,
      "y": 5,
      "from": "W"
    },
    "countdown": 20,
    "flameSpeed": 1.1,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1050,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## -- -- -- -- -- -- -- -- ## ## ##",
      "## ## -- -- -- -- -- -- -- -- -- -- ## ##",
      "## -- -- -- -- -- I1 I1 -- -- -- -- -- ##",
      "-- -- -- -- I1 I1 -- -- I1 I1 -- -- -- --",
      "-- -- I1 I1 -- -- -- -- -- -- I1 I1 -- --",
      "I1 I1 -- -- -- -- -- -- -- -- -- -- I1 I1",
      "-- -- -- -- -- -- ## ## -- -- -- -- -- --",
      "-- -- -- -- .. ## ## ## ## -- -- -- -- --"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ],
    "hint": "Seven short rails and a lot of empty tiles: build the road as you go."
  },
  {
    "id": 12,
    "name": "Two Hooks",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 4,
      "y": 2,
      "from": "W"
    },
    "countdown": 30,
    "flameSpeed": 1.1,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1100,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## ## -- -- -- -- -- -- ## ## ## ##",
      "## ## ## ## I1 I1 C2 -- -- -- ## ## ## ##",
      "## ## ## ## -- -- I0 C1 I1 I1 ## ## ## ##",
      "## ## ## ## I1 I1 C3 I0 -- -- ## ## ## ##",
      "## ## ## ## -- -- -- C0 I1 I1 ## ## ## ##",
      "## ## ## ## .. -- -- -- -- -- ## ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 13,
    "name": "Crossed Frame",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 4,
      "y": 1,
      "from": "N"
    },
    "countdown": 30,
    "flameSpeed": 1.1,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1150,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## .. -- -- -- -- -- C2 -- ## ## ##",
      "## ## ## C1 X0 I1 I1 I1 I1 X0 -- ## ## ##",
      "## ## ## -- I0 -- -- -- -- I0 -- ## ## ##",
      "## ## ## -- I0 -- ## ## -- I0 -- ## ## ##",
      "## ## ## -- I0 -- ## ## -- I0 -- ## ## ##",
      "## ## ## -- I0 -- -- -- -- I0 -- ## ## ##",
      "## ## ## -- X0 I1 I1 I1 I1 X0 C3 ## ## ##",
      "## ## ## -- C0 -- -- -- -- -- -- ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 14,
    "name": "Twin Blocks",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 11,
      "y": 3,
      "from": "N"
    },
    "countdown": 30,
    "flameSpeed": 1.1,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1200,
    "fuelPerTile": 0,
    "rows": [
      "## C1 I1 X0 X0 I1 C2 -- C1 I1 X0 X0 C2 ##",
      "## I0 -- I0 I0 -- I0 I0 I0 -- I0 I0 I0 ##",
      "## I0 -- I0 I0 -- I0 I0 I0 -- I0 I0 I0 ##",
      "## C0 I1 X0 X0 I1 C3 I0 C0 I1 X0 X0 C3 ##",
      "## C1 I1 X0 X0 I1 C2 .. C1 I1 X0 X0 C2 ##",
      "## I0 -- I0 I0 -- I0 I0 I0 -- I0 I0 I0 ##",
      "## I0 -- I0 I0 -- I0 I0 I0 -- I0 I0 I0 ##",
      "## C0 I1 X0 X0 I1 C3 -- C0 I1 X0 X0 C3 ##"
    ],
    "scramble": "",
    "tags": [
      "blodia",
      "approximation"
    ]
  },
  {
    "id": 15,
    "name": "Clover",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 4,
      "y": 3,
      "from": "W"
    },
    "countdown": 80,
    "flameSpeed": 1.1,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1250,
    "fuelPerTile": 0,
    "rows": [
      "-- -- -- C1 C2 -- -- -- -- -- C1 C2 -- --",
      "-- -- C1 C3 C0 C2 -- -- -- -- I0 C0 C2 --",
      "-- -- C0 C2 C1 C3 -- -- -- .. I0 C1 C3 --",
      "-- -- -- C0 C3 -- -- C1 C2 C1 C3 C0 C2 --",
      "C1 I1 C2 C1 I1 I1 I1 C3 C0 C3 -- -- I0 --",
      "C0 C2 I0 C0 I1 I1 C2 ## C1 I1 I1 C2 I0 --",
      "-- I0 I0 C1 I1 C2 I0 -- I0 -- -- C0 C3 --",
      "-- C0 C3 C0 I1 C3 C0 I1 C3 -- -- -- -- --"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 16,
    "name": "Knot",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 7,
      "y": 2,
      "from": "E"
    },
    "countdown": 30,
    "flameSpeed": 1.2,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1300,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## X0 Z1 ## ## ## ## ## ##",
      "## ## ## I1 I1 I1 X0 Z0 -- -- -- ## ## ##",
      "## ## ## .. -- C1 X0 Z0 I1 I1 I1 ## ## ##",
      "## ## ## ## ## ## I0 X0 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia",
      "approximation"
    ]
  },
  {
    "id": 17,
    "name": "Ring and Arc",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 6,
      "y": 2,
      "from": "E"
    },
    "countdown": 30,
    "flameSpeed": 1.2,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1350,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##",
      "## ## ## .. -- -- -- -- -- -- -- ## ## ##",
      "## ## ## -- C1 I1 I1 C2 -- -- C1 ## ## ##",
      "## ## ## C1 C3 -- ## C0 C2 C1 C3 ## ## ##",
      "## ## ## C0 C2 -- -- C1 C3 C0 C2 ## ## ##",
      "## ## ## -- C0 I1 I1 C3 -- -- C0 ## ## ##",
      "## ## ## -- -- -- -- -- -- -- -- ## ## ##",
      "## ## ## ## ## ## ## ## ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 18,
    "name": "Waves",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 12,
      "y": 7,
      "from": "S"
    },
    "countdown": 30,
    "flameSpeed": 1.2,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1400,
    "fuelPerTile": 0,
    "rows": [
      "-- I0 I0 -- -- -- C1 C2 -- -- -- -- -- I0",
      "I1 X0 X0 I1 I1 I1 C3 C0 I1 I1 I1 I1 I1 X0",
      "-- I0 C0 I1 C2 C1 C2 C1 C2 C1 .. -- C1 C3",
      "-- I0 -- -- C0 C3 C0 C3 C0 C3 -- -- I0 --",
      "-- I0 -- C1 I1 I1 I1 I1 I1 I1 C2 -- I0 --",
      "-- I0 -- C0 I1 I1 I1 I1 I1 I1 C3 -- C0 C2",
      "I1 X0 C2 C1 I1 C2 C1 I1 C2 C1 I1 C3 -- I0",
      "-- I0 C0 C3 -- C0 C3 -- C0 C3 -- -- C1 C3"
    ],
    "scramble": "",
    "tags": [
      "blodia",
      "approximation"
    ]
  },
  {
    "id": 19,
    "name": "Spiral",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 10,
      "y": 0,
      "from": "N"
    },
    "countdown": 30,
    "flameSpeed": 1.2,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1450,
    "fuelPerTile": 0,
    "rows": [
      "-- -- .. -- -- -- -- -- -- -- I0 I0 -- --",
      "-- -- -- -- C1 I1 I1 I1 I1 C2 I0 I0 -- --",
      "-- -- -- -- I0 C1 I1 I1 C2 I0 C0 C3 -- --",
      "-- -- -- -- I0 I0 C1 C2 I0 I0 C1 C2 -- --",
      "-- -- -- -- X0 X0 Z1 C3 I0 I0 I0 I0 -- --",
      "-- -- -- -- I0 I0 C0 I1 C3 I0 I0 I0 -- --",
      "-- C1 I1 I1 I0 C0 I1 I1 I1 C3 I0 I0 -- --",
      "-- C0 I1 I1 C0 I1 I1 I1 I1 I1 X0 C3 -- --"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  },
  {
    "id": 20,
    "name": "Propeller",
    "width": 14,
    "height": 8,
    "win": "cover",
    "start": {
      "x": 6,
      "y": 4,
      "from": "W"
    },
    "countdown": 50,
    "flameSpeed": 1.2,
    "timeLimit": 0,
    "lookahead": 2,
    "baseScore": 1500,
    "fuelPerTile": 0,
    "rows": [
      "## ## ## ## ## ## C1 C2 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## C1 I1 I1 I1 I1 Z1 Z0 I1 I1 I1 I1 C2 ##",
      "## C0 I1 I1 I1 I1 Z0 Z1 .. I1 I1 I1 C3 ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## I0 I0 ## ## ## ## ## ##",
      "## ## ## ## ## ## C0 C3 ## ## ## ## ## ##"
    ],
    "scramble": "",
    "tags": [
      "blodia"
    ]
  }
];
