// AUTO-GENERATED by scripts/generate-levels.ts - do not edit by hand.
// Regenerate with: npm run levels:generate
import type { LevelDef } from '../LevelDef';

export const GENERATED_LEVELS: LevelDef[] = [
  {
    "id": 9,
    "name": "Ember 1",
    "width": 5,
    "height": 4,
    "rows": [
      "S1 I1 I1 C2 I0",
      "D3 I0 X0 I0 ..",
      "I0 G1 I1 C3 T0",
      "C3 I1 I0 T1 X0"
    ],
    "scramble": "L",
    "flameSpeed": 0.7,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 72271
  },
  {
    "id": 10,
    "name": "Kindling 1",
    "width": 5,
    "height": 4,
    "rows": [
      "I1 I1 C1 G3 D2",
      "X0 D3 I0 C2 X0",
      "S2 T2 I0 .. I1",
      "C0 I1 C3 X0 I0"
    ],
    "scramble": "L",
    "flameSpeed": 0.71,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 80190
  },
  {
    "id": 11,
    "name": "Tinder 1",
    "width": 5,
    "height": 4,
    "rows": [
      "X0 S1 C2 C1 I0",
      "C3 C0 I0 X0 I1",
      "C1 X0 I0 .. T3",
      "I1 G1 C3 C1 T2"
    ],
    "scramble": "L",
    "flameSpeed": 0.72,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.1,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 88109
  },
  {
    "id": 12,
    "name": "Smoulder 1",
    "width": 5,
    "height": 4,
    "rows": [
      "C0 C1 I1 C2 C3",
      "G2 I0 I1 I0 C0",
      "C0 C3 .. S0 C2",
      "T3 I0 I1 C0 I0"
    ],
    "scramble": "L",
    "flameSpeed": 0.73,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.1,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 96028
  },
  {
    "id": 13,
    "name": "Flicker 1",
    "width": 5,
    "height": 4,
    "rows": [
      "I1 X0 D3 I1 I1",
      "I0 C1 I1 I1 S3",
      ".. I0 T3 X0 C1",
      "I1 G0 T1 C0 C0"
    ],
    "scramble": "R",
    "flameSpeed": 0.74,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.1,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 103947
  },
  {
    "id": 14,
    "name": "Spark Trail 1",
    "width": 5,
    "height": 4,
    "rows": [
      "I0 I0 I1 X0 ..",
      "T1 D3 C1 G1 C2",
      "C0 D3 C3 X0 I0",
      "I0 C2 S1 I1 C3"
    ],
    "scramble": "D",
    "flameSpeed": 0.75,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 111866
  },
  {
    "id": 15,
    "name": "Hearth 1",
    "width": 5,
    "height": 4,
    "rows": [
      "G2 I1 C2 T1 D0",
      "I0 .. X0 C0 C2",
      "C0 I1 I1 I1 S3",
      "C1 C3 I1 T1 C0"
    ],
    "scramble": "LD",
    "flameSpeed": 0.76,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 1250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 119785
  },
  {
    "id": 16,
    "name": "Wick 1",
    "width": 5,
    "height": 4,
    "rows": [
      "C1 I1 I1 T1 G3",
      "S0 C0 C2 X0 ..",
      "C3 I1 I1 I1 I1",
      "I0 C0 T2 D2 I0"
    ],
    "scramble": "LU",
    "flameSpeed": 0.77,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 127704
  },
  {
    "id": 17,
    "name": "Brazier 1",
    "width": 6,
    "height": 5,
    "rows": [
      "I1 C2 C1 I1 I0 C2",
      "X0 D2 D1 I0 D1 I0",
      "D3 C0 C2 S1 C2 D3",
      "C1 I1 C3 C0 I0 G2",
      "I0 C1 .. D2 C0 C3"
    ],
    "scramble": "RR",
    "flameSpeed": 0.78,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 135623
  },
  {
    "id": 18,
    "name": "Lantern 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 I1 I1 I1 I1 S3",
      "I0 T2 C1 X0 T1 T2",
      "C0 I1 G3 T3 I1 I0",
      ".. X0 I0 C1 X0 D2",
      "C3 C2 D0 X0 I0 D1"
    ],
    "scramble": "RU",
    "flameSpeed": 0.79,
    "timeLimit": 50,
    "lookahead": 3,
    "baseScore": 1400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 143542
  },
  {
    "id": 19,
    "name": "Furnace 1",
    "width": 6,
    "height": 5,
    "rows": [
      "S2 C3 C0 C1 C0 I0",
      "I0 C2 C2 I0 X0 D0",
      "I0 C3 D0 .. T3 X0",
      "I0 C0 T3 C1 C2 I0",
      "C0 I1 I1 I1 G3 C1"
    ],
    "scramble": "DD",
    "flameSpeed": 0.8,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 151461
  },
  {
    "id": 20,
    "name": "Cinder 1",
    "width": 6,
    "height": 5,
    "rows": [
      "S1 I1 I1 I1 C2 D3",
      "I0 I1 C1 D1 I0 G2",
      "I1 I0 C3 I0 C0 C3",
      "T0 C0 T0 D1 .. D0",
      "I1 C2 D3 T2 D2 C1"
    ],
    "scramble": "RU",
    "flameSpeed": 0.81,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.4,
    "pickups": [
      {
        "x": 5,
        "y": 3,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 159380
  },
  {
    "id": 21,
    "name": "Ashfall 1",
    "width": 6,
    "height": 5,
    "rows": [
      "S1 C2 I0 T3 C1 T0",
      "C3 I0 X0 I1 C0 T1",
      ".. I0 C0 X0 I1 I1",
      "D3 I0 D0 T3 I0 I0",
      "D1 C0 G3 C0 C1 C3"
    ],
    "scramble": "RR",
    "flameSpeed": 0.82,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.4,
    "pickups": [
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 167299
  },
  {
    "id": 22,
    "name": "Blaze 1",
    "width": 6,
    "height": 5,
    "rows": [
      "X0 X0 I1 T0 D3 T2",
      "C1 G2 C3 X0 C3 I0",
      "C2 C0 I1 I1 T1 D3",
      "C2 C2 T2 C1 C0 C2",
      "I0 .. T0 C1 D1 S0"
    ],
    "scramble": "UU",
    "flameSpeed": 0.83,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.4,
    "pickups": [
      {
        "x": 5,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 175218
  },
  {
    "id": 23,
    "name": "Wildfire 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 S3 I1 X0 X0 C0",
      "I0 C1 I1 G3 I0 X0",
      "I0 I0 C3 D1 I1 I0",
      "C0 C3 C1 T0 T1 I1",
      "C3 I0 .. C0 C3 C3"
    ],
    "scramble": "UL",
    "flameSpeed": 0.84,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 1,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 183137
  },
  {
    "id": 24,
    "name": "Inferno 1",
    "width": 6,
    "height": 5,
    "rows": [
      "S1 C2 C1 X0 C1 T2",
      "I1 I0 I0 G2 C0 C0",
      "D3 C0 I1 C3 .. C1",
      "C0 D0 C2 D0 X0 T1",
      "C0 D0 I1 I0 C3 I1"
    ],
    "scramble": "LL",
    "flameSpeed": 0.85,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 3,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 191056
  },
  {
    "id": 25,
    "name": "Torchlight 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 S1 I1 I1 I1 C2",
      "D2 C0 D1 I1 G1 C3",
      "C1 I1 C3 I1 T3 ..",
      "C2 T1 C3 I0 I1 I1",
      "T0 D3 C0 C2 I0 D0"
    ],
    "scramble": "UU",
    "flameSpeed": 0.86,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 1750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 198975
  },
  {
    "id": 26,
    "name": "Pyre 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 I1 C2 T2 D2 C2",
      "I0 T2 C0 I1 I1 G3",
      "I0 C3 I0 C0 I1 C2",
      "S0 I1 .. I1 I0 T3",
      "C0 D2 D0 I1 I0 C0"
    ],
    "scramble": "UU",
    "flameSpeed": 0.87,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.6,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 206894
  },
  {
    "id": 27,
    "name": "Backdraft 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 I1 I1 I1 C2 I0",
      "I0 T3 C1 D3 S0 I0",
      "G0 X0 X0 .. C2 C2",
      "C3 X0 I0 T1 C1 T3",
      "C3 D2 C0 I1 C3 C3"
    ],
    "scramble": "ULU",
    "flameSpeed": 0.88,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 1850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.6,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 214813
  },
  {
    "id": 28,
    "name": "Flashover 1",
    "width": 6,
    "height": 5,
    "rows": [
      "X0 D0 I1 T2 I1 I0",
      "I0 S1 C2 X0 I1 C1",
      "G2 T3 I0 C1 D2 I0",
      "I0 C1 T2 I1 C0 C2",
      "C0 I1 C3 .. T2 C2"
    ],
    "scramble": "LLU",
    "flameSpeed": 0.89,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 1900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.6,
    "pickups": [
      {
        "x": 0,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 222732
  },
  {
    "id": 29,
    "name": "Scorch 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C3 C2 C2 C1 I1 S3",
      "I1 I1 I0 T0 G1 C2",
      "X0 D1 I1 C0 I1 C3",
      "I0 C0 C1 I1 T2 D0",
      "X0 C2 T2 C0 X0 .."
    ],
    "scramble": "UUL",
    "flameSpeed": 0.9,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 1950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.7,
    "pickups": [
      {
        "x": 5,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 230651
  },
  {
    "id": 30,
    "name": "Sear 1",
    "width": 6,
    "height": 5,
    "rows": [
      "I0 T0 C3 D1 X0 I1",
      "I1 D2 C1 T1 S1 C2",
      ".. C3 D2 D1 I0 I0",
      "I1 X0 C1 I1 I1 C3",
      "D3 X0 C0 I1 I1 G3"
    ],
    "scramble": "RDR",
    "flameSpeed": 0.91,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.7,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 238570
  },
  {
    "id": 31,
    "name": "Char 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 S3 X0 I0 I1 T3",
      "C0 I1 I1 I1 G3 D2",
      "C0 C0 C2 C3 C1 X0",
      "C2 C2 I0 .. T0 I0",
      "X0 T0 X0 I1 C0 D2"
    ],
    "scramble": "UUL",
    "flameSpeed": 0.92,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.7,
    "pickups": [
      {
        "x": 3,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 246489
  },
  {
    "id": 32,
    "name": "Smoke Signal 1",
    "width": 6,
    "height": 5,
    "rows": [
      "X0 X0 S1 I1 I1 C2",
      "I1 I0 X0 D3 D3 I0",
      "I1 I1 C2 I0 I0 I0",
      "C1 C0 .. C3 G2 I0",
      "I1 C3 I0 D3 C0 C3"
    ],
    "scramble": "DRR",
    "flameSpeed": 0.93,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 5,
        "y": 0,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 254408
  },
  {
    "id": 33,
    "name": "Firebreak 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 I1 S3 C1 C3 C1",
      "C0 C2 I0 I0 .. C1",
      "C1 C3 X0 T2 T3 C1",
      "G0 T0 T1 C0 I0 C2",
      "C2 I1 I1 T3 I1 C1"
    ],
    "scramble": "LLL",
    "flameSpeed": 0.94,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 1,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 262327
  },
  {
    "id": 34,
    "name": "Flare 1",
    "width": 6,
    "height": 5,
    "rows": [
      "D3 C0 X0 C0 D0 D0",
      "T0 C3 D0 I1 D3 C2",
      "C1 I1 D2 I0 C1 G3",
      "C0 T2 .. S2 C0 C2",
      "T0 D1 X0 C0 I1 C3"
    ],
    "scramble": "URR",
    "flameSpeed": 0.95,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 270246
  },
  {
    "id": 35,
    "name": "Combustion 1",
    "width": 6,
    "height": 5,
    "rows": [
      "I1 C2 C2 D2 C1 S3",
      "I1 X0 D2 I1 I0 T2",
      "C3 X0 I0 T1 I0 I0",
      "C3 .. C1 I1 C3 C0",
      "T0 D0 G0 I0 X0 I1"
    ],
    "scramble": "RUL",
    "flameSpeed": 0.96,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.9,
    "pickups": [
      {
        "x": 2,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 278165
  },
  {
    "id": 36,
    "name": "Ignition 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C2 C3 I0 C3 C2 I0",
      "C0 C2 C0 C1 S2 I1",
      "C0 C2 T1 C0 I0 I1",
      "C3 C0 I0 .. I0 C1",
      "G1 I1 I1 I1 C3 I0"
    ],
    "scramble": "DRR",
    "flameSpeed": 0.97,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.9,
    "pickups": [
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 286084
  },
  {
    "id": 37,
    "name": "Heatwave 1",
    "width": 6,
    "height": 5,
    "rows": [
      "I1 T2 D2 I0 .. I0",
      "D1 I1 I0 T2 X0 C1",
      "C1 G3 T0 I1 I1 S3",
      "I0 X0 I0 I1 C0 D3",
      "C0 I1 C3 C1 I0 X0"
    ],
    "scramble": "LLD",
    "flameSpeed": 0.98,
    "timeLimit": 55,
    "lookahead": 3,
    "baseScore": 2350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.9,
    "pickups": [
      {
        "x": 2,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 294003
  },
  {
    "id": 38,
    "name": "Afterglow 1",
    "width": 6,
    "height": 5,
    "rows": [
      "T2 C2 C1 .. C1 C2",
      "C0 I1 C1 D1 I0 I0",
      "C1 I1 I1 S1 C3 I0",
      "I0 C2 I0 C1 C2 G0",
      "I1 C2 I0 C1 X0 X0"
    ],
    "scramble": "RRDD",
    "flameSpeed": 0.99,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3,
    "pickups": [
      {
        "x": 5,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 301922
  },
  {
    "id": 39,
    "name": "Ember 2",
    "width": 7,
    "height": 5,
    "rows": [
      "I0 D2 I0 D3 X0 S2 C2",
      "C2 I1 I1 I0 X0 I0 I0",
      "C2 I1 X0 C1 C2 I0 I0",
      "I0 .. T2 D1 I1 T3 C2",
      "C3 C0 G1 I1 T1 I1 C3"
    ],
    "scramble": "RRDR",
    "flameSpeed": 1,
    "timeLimit": 55,
    "lookahead": 3,
    "baseScore": 2450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3,
    "pickups": [
      {
        "x": 3,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 309841
  },
  {
    "id": 40,
    "name": "Kindling 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 I0 C3 .. C2 C1 C2",
      "C1 C2 I1 C0 C2 S0 I0",
      "I0 D3 C3 C1 I0 I1 I0",
      "I1 C3 D2 I0 C3 I0 I0",
      "T1 G1 I1 I1 I1 I1 C3"
    ],
    "scramble": "DDDD",
    "flameSpeed": 1.01,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3,
    "pickups": [
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 317760
  },
  {
    "id": 41,
    "name": "Tinder 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C1 I0 C0 X0 C2 C0 S2",
      "T3 D0 I1 T1 C3 C2 I0",
      "X0 C1 I1 I1 X0 T3 C3",
      "I1 I0 C1 C2 C3 C2 C2",
      "C3 G0 D1 C0 T3 .. C1"
    ],
    "scramble": "UUUU",
    "flameSpeed": 1.02,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 1,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 325679
  },
  {
    "id": 42,
    "name": "Smoulder 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C1 I1 C2 T0 C2 I0 ..",
      "C0 C2 C0 C2 C3 D3 C1",
      "S1 C3 G1 C3 I1 C3 T3",
      "D0 C1 I1 C3 C3 C1 I0",
      "T3 T0 X0 C0 X0 D0 X0"
    ],
    "scramble": "LDLL",
    "flameSpeed": 1.03,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 2,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 333598
  },
  {
    "id": 43,
    "name": "Flicker 2",
    "width": 7,
    "height": 5,
    "rows": [
      "I0 T3 I1 C1 G3 I0 D2",
      "D0 C0 C0 I0 I0 C1 C0",
      "I1 X0 .. I0 T0 X0 C3",
      "I0 D1 I1 C0 C2 C2 X0",
      "S1 I1 I1 I1 C3 C3 T3"
    ],
    "scramble": "RUUL",
    "flameSpeed": 1.04,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 341517
  },
  {
    "id": 44,
    "name": "Spark Trail 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C1 C2 T3 X0 X0 C0 C2",
      "I0 I0 X0 C0 X0 C0 ..",
      "I0 C0 I1 I1 I1 G3 D0",
      "I0 D2 C1 C1 I1 I0 C1",
      "S0 C1 X0 X0 X0 D3 I1"
    ],
    "scramble": "LLDL",
    "flameSpeed": 1.05,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.2,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 349436
  },
  {
    "id": 45,
    "name": "Hearth 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 I0 D0 X0 C2 I1 I0",
      "C1 C2 .. C3 C3 C1 X0",
      "S0 I0 T2 C3 I1 T0 C2",
      "D1 I0 C0 I1 C2 T1 G2",
      "D0 C0 I1 I1 I1 I1 C3"
    ],
    "scramble": "RDDD",
    "flameSpeed": 1.06,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.2,
    "pickups": [
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 357355
  },
  {
    "id": 46,
    "name": "Wick 2",
    "width": 7,
    "height": 5,
    "rows": [
      "X0 C1 C1 I1 T1 C1 C2",
      "C3 I1 C3 C1 C1 C3 G0",
      "T0 I1 D3 T2 I0 D0 ..",
      "I0 C2 D2 T1 C0 C2 C0*",
      "C3 C3 T3 S1 I1 C3 C2"
    ],
    "scramble": "LLUL",
    "flameSpeed": 1.07,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.2,
    "pickups": [
      {
        "x": 5,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 365274
  },
  {
    "id": 47,
    "name": "Brazier 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 I1 C2 I1 C1 C1 T0",
      "C1 X0 .. C1 I1 C2 C2",
      "T3 I0 C3 I0 X0 G0 C2",
      "I1 X0 C1 T2 T2 C3 T1",
      "I1 S1 C3 D0 C3* C1* I0"
    ],
    "scramble": "RRUR",
    "flameSpeed": 1.08,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.3,
    "pickups": [
      {
        "x": 3,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 373193
  },
  {
    "id": 48,
    "name": "Lantern 2",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 C1 C1 I1 S3 I0 C3",
      "X0 G2 I0 D3 D2 C3 C0",
      "D2 I0 I0 C0 C3 I0 C3",
      "T0 I0 I0 .. D0 C0 I1",
      "I1 C0 C3 X0 C1 D0 I0"
    ],
    "scramble": "ULLD",
    "flameSpeed": 1.09,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.3,
    "pickups": [
      {
        "x": 1,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 381112
  },
  {
    "id": 49,
    "name": "Furnace 2",
    "width": 7,
    "height": 5,
    "rows": [
      "I1 X0 I0 G1 C2 I1 D3",
      "I0 T1 C1 C3 I0 D0 C3",
      "I1 C2 I0 C1 I0 C2 ..",
      "C3 C1 C3 C0 I0 C1 C3",
      "C3 S1 I1 I1 C3 C0 T0"
    ],
    "scramble": "LLULD",
    "flameSpeed": 1.1,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.3,
    "pickups": [
      {
        "x": 5,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 389031
  },
  {
    "id": 50,
    "name": "Cinder 2",
    "width": 7,
    "height": 5,
    "rows": [
      "I0 T0 C2 D2 C1 I1 C2",
      "T2 T2 C2 C1 C3 C1 C3",
      "X0 I0 G1 C3 S1 C3 I0",
      "I0 .. D1 I1 C3 D3 D0",
      "I0 C2 I0 D2 X0 I1 X0"
    ],
    "scramble": "DRRUU",
    "flameSpeed": 1.11,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 3000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "ember"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 396950
  },
  {
    "id": 51,
    "name": "Ashfall 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C3 C3* I0 C0 C2 C3 C0",
      "C3 I0 I1 I0 D3 I1 C2",
      "C1 S1 I1 I1 I1 I1 C2",
      "C0 I0 I1 C0 T1 C3 I0",
      "C2 C3 I0 C1 G1 I1 C3",
      "I1 C0 I1 I0 C3 .. X0"
    ],
    "scramble": "UUUUL",
    "flameSpeed": 1.12,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 404869
  },
  {
    "id": 52,
    "name": "Blaze 2",
    "width": 7,
    "height": 6,
    "rows": [
      "X0 D0 D0 G2 D3 C3 I1",
      "C0 X0 T3 I0 I0 I1 C1",
      "I1 D2 D2 I0 X0* C3 C3",
      ".. C2 C0 I0 I0 X0 I0",
      "I1 I0 I1 C0 I1 I1 C2",
      "I1 C3 S1 I1 I1 I1 C3"
    ],
    "scramble": "RURRU",
    "flameSpeed": 1.13,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 6,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 412788
  },
  {
    "id": 53,
    "name": "Wildfire 2",
    "width": 7,
    "height": 6,
    "rows": [
      "G2 C1 I1 T1 X0 I1 C2",
      "I0 I0 X0 C3 C1 I1 C3",
      "C0 C3 C2 C3 S0 X0 ..",
      "C3 C3 C3 X0 I1 C0 X0",
      "C3 I0 T0 C3 I1 C2 C1",
      "C1 C3 I0 C0 C0 C3 I0"
    ],
    "scramble": "DLURU",
    "flameSpeed": 1.14,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 6,
        "y": 1,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 420707
  },
  {
    "id": 54,
    "name": "Inferno 2",
    "width": 7,
    "height": 6,
    "rows": [
      "T2 C0 D0 C1 I0 D0 C0",
      "D0 D0 X0 D3 S2 C2 D1",
      "I1 T2 X0 I1 I0 D1 X0",
      "D3 C1 C2 D3 I0 .. T2",
      "C2 G0 I0 C1 C3 I1 I0",
      "T1 C1 C0 C3 D1 T0 T1"
    ],
    "scramble": "DLLUL",
    "flameSpeed": 1.15,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 3,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 428626
  },
  {
    "id": 55,
    "name": "Torchlight 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C0 C3 C1 X0 D2 I0* C3",
      "T0 D3 T1 T0 C3 I1 T2",
      "I1 C3 I1 I1 C2 G2 I0",
      "I1 I1 C1 .. C2 C0 C2",
      "I0 S1 I1 I1 C2 C1 I0",
      "X0 D2 C1 C1 C0 I1 C3"
    ],
    "scramble": "RDRRU",
    "flameSpeed": 1.15,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 436545
  },
  {
    "id": 56,
    "name": "Pyre 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C3 G1 C2 I1 D3 I0 X0",
      "D3* T0 I0 D1 D2 X0 C2",
      "T1 I1 I0 X0 I0 S2 X0",
      "C3 T2 I0 .. C1 C3 I1",
      "T1 D0 C0 C2 T2 D2 C2",
      "D1 X0 T2 C0 C3 T2 I1"
    ],
    "scramble": "DLLLU",
    "flameSpeed": 1.16,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 444464
  },
  {
    "id": 57,
    "name": "Backdraft 2",
    "width": 7,
    "height": 6,
    "rows": [
      "X0 X0 I1 I1 D1 I1 C1",
      "S2 C1 G3 I1 D2 I1 I1",
      "I0 I0 C3* T1 C3 I1 C0",
      "I0 I0 I1 I0 T3 .. I1",
      "T2 C0 C2 I1 D3 C1 T1",
      "C0 I1 C3 C2* T0 I0* D2"
    ],
    "scramble": "LDLLL",
    "flameSpeed": 1.17,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 1,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 452383
  },
  {
    "id": 58,
    "name": "Flashover 2",
    "width": 7,
    "height": 6,
    "rows": [
      "T3 D3 T1 C1 I1 I1 C2",
      "C2 X0 C0 I0 C1 I1 C3",
      "T2 S2 C1 C3 G0 .. C1",
      "C3 C0 T2 I0 I0 C2 D3",
      "C3 I1 I0 D0 I0 T2 C3",
      "C3 I0 D0 X0 C2 I1 T2"
    ],
    "scramble": "UULDR",
    "flameSpeed": 1.18,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 3400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 460302
  },
  {
    "id": 59,
    "name": "Scorch 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C1 I1 X0 I1 I1 I1 C2",
      "C0 C2 C0 I0 C3 I1 I0",
      "I0 S0 C0 T3* X0 X0 G0",
      "X0 D3 .. C1 C0 I1 T1",
      "C3 C2 C0 C0 T0 I1 I0",
      "T1 I1 C2 C3 X0 X0 D3"
    ],
    "scramble": "UUURR",
    "flameSpeed": 1.19,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 0,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 468221
  },
  {
    "id": 60,
    "name": "Sear 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C1 I1 I1 I1 I1 G3 I0",
      "I0 I0 I1 C3 C1 C2 C2",
      "I0 T0 .. I1 I1 I1 C2",
      "I0 C0 T1 D2 T1 C0 X0*",
      "T2 I1 C2 C3 T3 T2 C0",
      "C0 T1 I1 S3 C2 I0 X0"
    ],
    "scramble": "LDDLU",
    "flameSpeed": 1.2,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.7,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 476140
  },
  {
    "id": 61,
    "name": "Char 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C1 I1 G3 C3 I1 D1* D1",
      "C0 I1 C2 I1 D3 X0 D0",
      "C1 I1 T2 D2 D0 X0 C3",
      "I0 I0 I0 I0 T2 D1 D2",
      "S0 X0 D0 T1 T1 D2 ..",
      "C3 C2 X0 T0 C3 T2 C0"
    ],
    "scramble": "LULLUL",
    "flameSpeed": 1.21,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.7,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 484059
  },
  {
    "id": 62,
    "name": "Smoke Signal 2",
    "width": 7,
    "height": 6,
    "rows": [
      "I0 I0 X0* T0 C0 C1 D0",
      "T3 C3 D2 C2 T2 C2 X0",
      "I0 T0 .. I0 T3 C3 I1",
      "X0 S1 I1 I1 C2 X0 I0",
      "D0 C1 I1 C2 I0 C1 I1",
      "D1 T3 G3 C0 C3 I0 D1"
    ],
    "scramble": "LLDDRR",
    "flameSpeed": 1.22,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.7,
    "pickups": [
      {
        "x": 4,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 491978
  },
  {
    "id": 63,
    "name": "Firebreak 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C1 C1 X0 C1 S1 C2 C1",
      "C0 D2 C2 D0 C2 I0 C1",
      "I1 I0 T2 D1 I1 T3 C2",
      "X0 T0 I1 I1 X0 I1 C3",
      "G2 I0 .. I1 T0 I1 C0",
      "C0 C3 C0 I0 D0 I1 X0"
    ],
    "scramble": "DLUURD",
    "flameSpeed": 1.23,
    "timeLimit": 70,
    "lookahead": 2,
    "baseScore": 3650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.8,
    "pickups": [
      {
        "x": 1,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 2,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 499897
  },
  {
    "id": 64,
    "name": "Flare 2",
    "width": 8,
    "height": 6,
    "rows": [
      "D3 .. I1 D3 D2 I0 D0 I1",
      "I1* I0 C0 I1 D2 I1 D3 C3",
      "C0 C1 C2 I0 I0 C1* X0 C2",
      "C1 C0 I1 C0 T0 I1 I1 C2",
      "C1 G3 C3 I0 I0 S1 C2 I0",
      "C0 T1 I1 T1 C3 T0 C0 C3"
    ],
    "scramble": "RDDRUR",
    "flameSpeed": 1.24,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 3700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.8,
    "pickups": [
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 507816
  },
  {
    "id": 65,
    "name": "Combustion 2",
    "width": 8,
    "height": 6,
    "rows": [
      "X0 .. C1 C1 T0 I1* T1 C3",
      "C0 I0 T2 C2 I1 C0 C2 X0",
      "C2 C1 I1 I1 G3 T3 I1 D2",
      "I0 I0 T2 T0 I1 D1 C0 C3",
      "C1 C3 T3 C2 C0 C3 I0 I0",
      "C0 I1 T3 I1 I1 I1 S3 X0*"
    ],
    "scramble": "DLURDD",
    "flameSpeed": 1.25,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.8,
    "pickups": [
      {
        "x": 0,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 515735
  },
  {
    "id": 66,
    "name": "Ignition 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 X0 I1 X0 C2 G1 I1 C2",
      "C3 T0 T1 C1 I1 I1 I1 C3",
      "X0 D1 C0 I0 .. T2 X0 I0",
      "C0 T3 D1* T0 I1 X0 I1 D0",
      "X0 I1 T2 I0 S1 I1 C2 T0",
      "T3 I1 C2 C0 I1 I1 C3 T2"
    ],
    "scramble": "DLUURD",
    "flameSpeed": 1.26,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 3800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 6,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 523654
  },
  {
    "id": 67,
    "name": "Heatwave 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 T0* I1 T1 I0 C3 T1 I0",
      "I0 D1 I0 D3 X0 .. I0 C3",
      "C3 I0 S1 I1 T3 C2 I1 T1",
      "T3 I0 I0* C1 C2 I0 T1 T1",
      "I1 T3 C3 T0 G0 I0 C3 C3",
      "I1 C0 C3 C0 I1 C3 I0 I0"
    ],
    "scramble": "DDDDRU",
    "flameSpeed": 1.27,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 531573
  },
  {
    "id": 68,
    "name": "Afterglow 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 C2 .. T0 I0 I0 X0 I1",
      "X0 C3 D2 X0 I0 X0 X0 X0",
      "I1 C0 C0 T2 C1 T1 I1 C2",
      "S2 C1 C2 T2 I0 X0 I0 G0",
      "I0 I0 C0 T1 C3 C3 T0 T3",
      "C0 C3 T0 C2 D0 I0* T1 X0"
    ],
    "scramble": "DRDDDD",
    "flameSpeed": 1.28,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 539492
  },
  {
    "id": 69,
    "name": "Ember 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 C2 C3 I1 I0 X0 T1 I0",
      "I0 S0 X0 C2 T1 .. I0 T0",
      "X0 T2 D2 C1 I1 D3 C2 T0",
      "I0 C1 G1 C2 I1 D3 C3 T3",
      "I0 C1 X0 T2 C3 I0 C3 C3",
      "C0 C3 T3 D0 D0 D1 I1 C1"
    ],
    "scramble": "DLULDD",
    "flameSpeed": 1.29,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4,
    "pickups": [
      {
        "x": 3,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 547411
  },
  {
    "id": 70,
    "name": "Kindling 3",
    "width": 8,
    "height": 6,
    "rows": [
      "X0 .. I1 I1 C1 D2 I0 T2",
      "C1 X0 D2 I0 C3 T0 X0 C2",
      "C1 I0 D2 C1 C3 G0 I1 X0",
      "S1 I1 I1 I1 I1 X0 T1 C3",
      "T3 X0 D1 C3 C2 T3* D1 I0",
      "C0 I1 T0 I0 T1 X0 T0 D0"
    ],
    "scramble": "RRRDRR",
    "flameSpeed": 1.3,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4,
    "pickups": [
      {
        "x": 5,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 555330
  },
  {
    "id": 71,
    "name": "Tinder 3",
    "width": 8,
    "height": 6,
    "rows": [
      ".. C0 C0 X0 C2 G2 C1 C2",
      "X0 C1 T0 C1 X0 C0 I1 C2",
      "D3 I1 C0 D0 T0 D2 C2 T0",
      "C1 C0 C3 X0 I1 T0 C2 I0",
      "I0 I0* C1 C2 T1 X0 S0 T0",
      "C1 C0 D3 C2 T0* C0 I1 C3"
    ],
    "scramble": "RRDRRR",
    "flameSpeed": 1.31,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4,
    "pickups": [
      {
        "x": 7,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "ember"
      },
      {
        "x": 7,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 563249
  },
  {
    "id": 72,
    "name": "Smoulder 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 X0 T1 T0 C2 I0 C3 C3",
      "I1 C3 C0 D0 C1 I1 S3 C2",
      "X0 C1 C0 X0 I0 D2 X0 C0",
      "C1 C1 C2 .. I0 C1 C2 D3",
      "T0 C3 C0 T1 I0 G0 C0 C2",
      "C3 C2 D1 I1 T3 I1 I1 C3"
    ],
    "scramble": "RDDLLLL",
    "flameSpeed": 1.32,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.1,
    "pickups": [
      {
        "x": 4,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 571168
  },
  {
    "id": 73,
    "name": "Flicker 3",
    "width": 8,
    "height": 6,
    "rows": [
      "T3 C1 I1 C1 I0 .. I1 I0",
      "I0 C1 C2 D2 C3 D0 C1 I0",
      "C1 I0 C0 I1 I1 I1 I1 G3",
      "C1 C0 T1 I1 C2 S2 I0 C1",
      "D1 I0 C0 X0 I0 I0 C2 I0",
      "C1 I0 I0 C3 C0 C3 I1* I1"
    ],
    "scramble": "LLLLDDD",
    "flameSpeed": 1.33,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.1,
    "pickups": [
      {
        "x": 1,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 579087
  },
  {
    "id": 74,
    "name": "Spark Trail 3",
    "width": 8,
    "height": 6,
    "rows": [
      "X0 X0 C1 I1 I1 C2 I1 D3",
      "C3 T2 I0 C0 T1 I0 G2 T3",
      "X0 C3 I0 C1* I0 S0 C0 C2",
      "X0* I0 C0 I1 I1 T3 I1 T2",
      "C1 C3 C3 C2 C0 .. C1 I0",
      "X0 I0 X0 T0* T3 I0 C3* D0"
    ],
    "scramble": "ULDDRUU",
    "flameSpeed": 1.34,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.1,
    "pickups": [
      {
        "x": 6,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 587006
  },
  {
    "id": 75,
    "name": "Hearth 3",
    "width": 8,
    "height": 6,
    "rows": [
      "G1 T1 T3 I1 C2 D3 S2 D3",
      "C0 X0 C0 C0 C0 C2 I0 C1*",
      "I0 C2 C3 I1 C3 I0 I0 I0",
      "C1 T1 D2 D0* C1 T2 I0 C1",
      "C1 D2 T2 I1 X0 D0 T0 D1*",
      "C1 C0 X0 .. C0 I1 C3 D1"
    ],
    "scramble": "LUUUURU",
    "flameSpeed": 1.35,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 2,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 594925
  },
  {
    "id": 76,
    "name": "Wick 3",
    "width": 8,
    "height": 6,
    "rows": [
      "T3 I1 C1 G3 D3* C1 X0 C0*",
      "C2 I0 I0 C1 I1 C3 I1 D3",
      "T3 T1 C0 I1 I1 I1 I1 C2",
      "I0 T3 T3 I1* I0 C0 S2 I0",
      "D2 .. D0 X0 C0 T3 I0 I0",
      "C1* C2 D0 C1 D1 I1 C0 C3"
    ],
    "scramble": "DRUUURU",
    "flameSpeed": 1.36,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 2,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 602844
  },
  {
    "id": 77,
    "name": "Brazier 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C3 C1 I1 D3 C2 D3 I0 C2",
      "C2 T1 C3 D0 S2 C1 T3 C2",
      "D1 C0 C1 T1 C0 C3 I0 I0",
      "X0 C2 C0 .. C1 T1 D3 I0",
      "X0 C2 C0 T1 I0 T0 C3 I0",
      "D0* C3 G1 I1 C3 C0 I1 C3"
    ],
    "scramble": "DDRUULD",
    "flameSpeed": 1.37,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 6,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 610763
  },
  {
    "id": 78,
    "name": "Lantern 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C0 C1 I1 I1 I1 C2 C2 X0",
      "C0 I0 I0 C1 I1 C3 C3 D3",
      "C0 I0 T1 I0 C2 T2 X0 ..",
      "C0 S0 I0 I0 T0 I0 I1 C2",
      "X0 C3 D0 I0 X0 I1 X0* C1*",
      "I0* C1 C3 G0 C0 C1 I0 X0"
    ],
    "scramble": "UULDLLD",
    "flameSpeed": 1.38,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.3,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 618682
  },
  {
    "id": 79,
    "name": "Furnace 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C2 C0 C2 C3 I0 T1 C2* C2",
      "X0 I1 T3 C2 .. C2* I0* C1",
      "C1 I1 T3 C2 C1 G3 T0 T1",
      "C0 C2 D3 I0 I0 C1 I0 C3",
      "S2 I0 C1 C3 I0 C3 C1 I0",
      "C0 C3 C0 I1 C3 I1 I1* I0"
    ],
    "scramble": "DLLLLUR",
    "flameSpeed": 1.39,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.3,
    "pickups": [
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 626601
  },
  {
    "id": 80,
    "name": "Cinder 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C3 C0 C1 I1 I1 C2 T1 I0",
      "X0 I0 I0 .. I1 I0 C1 C0",
      "I0 I1 T0 D1 C2 I0 I1 C0",
      "D3 C0 I0 D1 I1 T3 G3 C2",
      "C3 C1 C3 C1 S3 C0 T3 X0",
      "X0 C0 T1 C3 C0 C0 I0 I1"
    ],
    "scramble": "DDRRUUL",
    "flameSpeed": 1.4,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.3,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 634520
  },
  {
    "id": 81,
    "name": "Ashfall 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C3 C1 T3 I1 S3 C1 X0 C1",
      "D1 C0 T3 X0 I1 I1 I1 C2",
      "X0 C0 C3 C3 D2 C1 C2 I0",
      "T2 C0 X0 C3* T0 C0 C0 T0",
      "D1 T2 .. T0 C1 X0 T3 I0",
      "C0 C1 T2 I0 T1 C1 G1 C3"
    ],
    "scramble": "RRURDRR",
    "flameSpeed": 1.41,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.4,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 642439
  },
  {
    "id": 82,
    "name": "Blaze 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 I1 I1 T1 I1 I1 D3 X0",
      "T0 C3 X0 C0 I1 S3 I0 C0*",
      "I0 I0* I0 C1 X0 T1* I0 C1*",
      "I0 X0 .. D2 C3 C3 I1 C0",
      "T2 C3 T1 G2 D1 C2 C1 C1",
      "C0 I1 I1 C3 I1 I0 X0 C2"
    ],
    "scramble": "UULLURD",
    "flameSpeed": 1.42,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.4,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 650358
  },
  {
    "id": 83,
    "name": "Wildfire 3",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 I1 I1 I0 C3 C1 C2 I1*",
      "C1 I1 I1 X0 C2 I0 S0 T0",
      "G0 T2 D1 D3 I0 I0 I0 I0",
      "D0 I1 D0 I1 C0 C3 X0 C0",
      "D1 T1 D3 X0 X0 I0 I1 D1",
      "T0* C1 C3 C0 I1 T3* C3 .."
    ],
    "scramble": "UUULLDLL",
    "flameSpeed": 1.43,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 4650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.4,
    "pickups": [
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 658277
  },
  {
    "id": 84,
    "name": "Inferno 3",
    "width": 8,
    "height": 6,
    "rows": [
      "I0 C3 C1 I1 C2 C2 I0 D3",
      "D1 X0 I0 I0* G0 D2 C0 C1",
      "D2 X0 I0 I0* X0 I0 .. T3",
      "C2 D3 I0 D0 I1 I0 S2 D2",
      "D3 I1* C0 I1 C2 T0 C3 C2",
      "C0 T3 D2 C1 C0 C3 I1* D2"
    ],
    "scramble": "RUULLLLL",
    "flameSpeed": 1.44,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 666196
  },
  {
    "id": 85,
    "name": "Torchlight 3",
    "width": 8,
    "height": 6,
    "rows": [
      "D0 C1 I1 I0* C1 C1 C3* C3",
      "C1 I1 X0 I1 T1 G3 C1 C0",
      "T2 D3* T2 T2 D1 I0 T3 C3",
      "T2 X0 .. I0 C3* C1 C0 X0",
      "I0 D2 C1 T1 I0 C0 T0 S2",
      "C0 I1 T1 I1 I1 I1 I1 C3"
    ],
    "scramble": "DDLULDRU",
    "flameSpeed": 1.45,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 4,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 674115
  },
  {
    "id": 86,
    "name": "Pyre 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 I1 C2 S2 .. D3 I1 C3*",
      "C0 C2 T2 I0 X0 T0 I1 I0",
      "C1 C3 G0 I0 D0 T2 C0 T3*",
      "I0 I0 D2 I0 C1 C1 I1 C1",
      "I0 D0 T0 C3 C1 C2 I1 C2",
      "C0 I1 C3 C1* D0 T2* C1 X0"
    ],
    "scramble": "RDLDDLLD",
    "flameSpeed": 1.46,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 0,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 682034
  },
  {
    "id": 87,
    "name": "Backdraft 3",
    "width": 8,
    "height": 6,
    "rows": [
      ".. I1 D3* X0 X0 T2 C2 G2",
      "C3 C3 D1 D1 C0 C3 C1 C3",
      "D2* I1 X0 T3 C1 C2 C0 C2",
      "I0 D3 C2* C2 I0 C0 I1 T2",
      "C0* C2 X0 T2 I0 S2 I0 I0",
      "C2 I1 C2 X0 C0 C3 D3 D0"
    ],
    "scramble": "DRRDRRDD",
    "flameSpeed": 1.47,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.6,
    "pickups": [
      {
        "x": 7,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 689953
  },
  {
    "id": 88,
    "name": "Flashover 3",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 I1 C2 C0 I1* C3 X0 T1",
      "T0 C1 C3 G2 I1 C0 C1 C1",
      "I0 I0 I0 T0 C2 X0 I1 I0",
      "I0 I0 .. T2 C1 C2* D2 T1",
      "S0 X0 I1 I0 C3 C2 C1* T3",
      "D1 C0 I1 C3 T3 C1 C3 I0"
    ],
    "scramble": "LUUURDDL",
    "flameSpeed": 1.48,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.6,
    "pickups": [
      {
        "x": 1,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 697872
  },
  {
    "id": 89,
    "name": "Scorch 3",
    "width": 9,
    "height": 7,
    "rows": [
      "I0 D1 D2 C0 X0* D0 X0 C3 D0",
      "C2 D3 .. S2 I0 C2 I0* G2 X0",
      "D3 C0 C2 I0 I1 D3 C2 I0 C3",
      "I1 C1 T1 C3 D2 T3 C3 T2 C0",
      "I0 I0 C1 T0 I1 D1 C3 I0 X0",
      "I1 I0 C0* C2 C3 C3* T3 I0 X0",
      "D1 C0 T1 I1 I1 I1 I1 C3 I0"
    ],
    "scramble": "LDRDLLUR",
    "flameSpeed": 1.49,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 4950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.6,
    "pickups": [
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 6,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 705791
  },
  {
    "id": 90,
    "name": "Sear 3",
    "width": 9,
    "height": 7,
    "rows": [
      ".. I0 C1 I0 X0 C3* X0 X0 I0",
      "C1 I1 I1 T1 T3 I1 G3 I0 X0",
      "I0 S2 T1 C2 C0 I1 I1 C2 I1",
      "I0 I0 T2 C0 T0 I1 X0 D1 C1",
      "I0 X0 C2* I0 C3 C3* D0 C1* D1",
      "I0 I0 X0 I0* I1 C2 I1 I0 C0",
      "C0 C3 C0 C1 C2 C3 D1 T0 T0"
    ],
    "scramble": "DDDDDRRD",
    "flameSpeed": 1.5,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 5,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 713710
  },
  {
    "id": 91,
    "name": "Char 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C1 I1 S3 C3 C1 D1 C2 D0* I1",
      "I0 .. T3 X0 D2* I1 C3 C0 I1",
      "I0 C2 T1 X0 C2 C1 C3 X0 C2",
      "C0 I1 C2 I0 C0 X0 I1 T1 C0",
      "C1 C2 I0 C2 C1 C0* I1 I1 T2",
      "T0 G0 I0 X0 D1 C1 I1 C1 C2",
      "C0 X0 C3 I0 C3 D3 C2* X0 C2"
    ],
    "scramble": "LDDDRRRR",
    "flameSpeed": 1.51,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 6,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 721629
  },
  {
    "id": 92,
    "name": "Smoke Signal 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C1 I1 S3 C2 I1 C3 I1 T2 X0",
      "C0 C2 I1 X0 I0* I1 D3 C0 C3",
      "C1 C3 D3 T2 D2* I1* D1 C3 ..",
      "X0 I1 C0* C1 C3* I0* I1 X0 I1",
      "I0 I0 X0 X0 C1 T0 X0 D0 D0",
      "I0 C0 C1 C2 D1* D2 C3 I1 C0",
      "C0 I1 C3 C0 I1 I1 I1 I1 G3"
    ],
    "scramble": "DDDLDLUU",
    "flameSpeed": 1.52,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 1,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 729548
  },
  {
    "id": 93,
    "name": "Firebreak 3",
    "width": 9,
    "height": 7,
    "rows": [
      "T1 .. D2 C1 I1 I1 T1 I1 C2",
      "I0 D2 C2 C0 I1 I1 S3 C3* T2",
      "T1 C2 I1 C3 G1 C2 C1 I1 C3",
      "C0 D2 C1 X0 C2 C0 C3 C1* C0",
      "T0 T3 X0 X0 C3 I0 C2 C3 C3",
      "D1 I0 T0 C3 X0 I1 D0 C1 I1",
      "I1 C0 C3* D3 C2* C3 X0 C3 C3"
    ],
    "scramble": "DLURRRRR",
    "flameSpeed": 1.53,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 5150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.8,
    "pickups": [
      {
        "x": 7,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 737467
  },
  {
    "id": 94,
    "name": "Flare 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C2* C0 C3 X0 D1 C0 .. C1 C3",
      "C1 T1 C2 C0 D2 X0 D2 C2* T1*",
      "S0 I1 I0 X0 T3 T3 I0 C0 C3*",
      "D1 I1 C0 I1 T3 C2 I0 T0 X0",
      "C3 I1 C1 T0 C0 I0 C1 I1 C2",
      "I1* C0 C0 I0 T3 T2 C0 G3 T0",
      "I0 C3 D1 I1 I1 C0 I1 I1 C3"
    ],
    "scramble": "DDRDLLLL",
    "flameSpeed": 1.54,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.8,
    "pickups": [
      {
        "x": 6,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 6,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 6,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 6,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 745386
  },
  {
    "id": 95,
    "name": "Combustion 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C1 T1 X0 C2 C3* C1 X0 C1 C1",
      "I0 G1 I1 C3 C1 C0 X0 C3 I0",
      "C0 I1 T1 I1 I1 D3 .. T0 C2",
      "I1 C1 I0 C1 I0* I1 X0 I1 D1",
      "I0 C2 C0 T1 T3 C2 I1 I1 D3",
      "C3 I0 X0 I0 D1 I0 D3 C0 D3",
      "I1* C2 T1 C2 C2 S0 D0 C0 T1"
    ],
    "scramble": "DLULLLUUL",
    "flameSpeed": 1.55,
    "timeLimit": 60,
    "lookahead": 1,
    "baseScore": 5250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.8,
    "pickups": [
      {
        "x": 2,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "ember"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 4,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 753305
  },
  {
    "id": 96,
    "name": "Ignition 3",
    "width": 9,
    "height": 7,
    "rows": [
      "X0 X0 .. C2 C1 C1 I1 T1 C2",
      "X0* C3 X0 C2 T1* I0 C2 C1 I0",
      "X0 I0 C0 C3 C1 C3 I0* D1 G0",
      "C1* T2* I1 I0* C0 C2 I1 I1 D3",
      "C1 C0 I0 I1 C0 T2 S2 I0 T1",
      "C3 C2 D3 C3 X0 I0 C0 C2 I0*",
      "I1 C0 I0 T2 T0 C0 I1 C3 T1*"
    ],
    "scramble": "RRRRRDLUR",
    "flameSpeed": 1.56,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 5300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.9,
    "pickups": [
      {
        "x": 8,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 761224
  },
  {
    "id": 97,
    "name": "Heatwave 3",
    "width": 9,
    "height": 7,
    "rows": [
      "X0 X0 I0 T0 D2 X0 C3 C1* C1",
      "I0* I1 D1 T2 C0 X0 C0 I1 T1",
      "X0 X0 D3 I1 C3 I0 C1 C0 I0",
      "C3 C2 I1 C0* I1 I1 C1 X0 I1",
      ".. C1 C1 I1 I1 T1 I1 X0 C2",
      "G2 C3 S0 C1 I1 I1 I1 C2 I0",
      "C0 I1 I1 C3 I1* X0 X0 C0 C3"
    ],
    "scramble": "URULDDRDD",
    "flameSpeed": 1.57,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.9,
    "pickups": [
      {
        "x": 4,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 769143
  },
  {
    "id": 98,
    "name": "Afterglow 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C3 C3 C0 D3 X0 C1 I1 I1 C2",
      "I1* C1 I1 I1 I1 C3 X0 X0 I0",
      "X0 C0 I1 I1 T1 I1 I1 D3 I0",
      "T0 I0 C1 C2 I0 .. C0 T2 I0",
      "I0 D0 I0 C1 I0 I1* D2 T2 T0",
      "C2 D1 I1 I0 I0 C3 C3 D0 G0",
      "S1 I1 I1 I1 C3 C2 C1 T1 D2*"
    ],
    "scramble": "ULLULLDRU",
    "flameSpeed": 1.58,
    "timeLimit": 75,
    "lookahead": 1,
    "baseScore": 5400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.9,
    "pickups": [
      {
        "x": 8,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 777062
  },
  {
    "id": 99,
    "name": "Ember 4",
    "width": 9,
    "height": 7,
    "rows": [
      "T3* X0 T2 D0 D2 C0 C0 I0 D1",
      "I1 C3 X0 T1 T3 .. C1 C0 C0",
      "C3 X0* D3 C1 X0 C1 C2 C0 C3",
      "X0 C1 I1 T1 I1 C3 X0 C3 I1",
      "S2 C0 T3 C2 I1 D3 T0 C3* D0",
      "I0 I0 D0 X0 T1 T0 G0 T2* D0",
      "C0 I1 I1 C3 D1 C2 D3 D3* T0"
    ],
    "scramble": "RRRULDLDD",
    "flameSpeed": 1.59,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 5450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 5,
    "pickups": [
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 784981
  },
  {
    "id": 100,
    "name": "Kindling 4",
    "width": 9,
    "height": 7,
    "rows": [
      "X0 C2* I1 C2 C2 I0 C2 T2 C1",
      "C1 G2 I0 T1 I0 T0* C3 C2 ..",
      "D3 C0 I1 I1 I1 I1 I1 I1 C2",
      "C0 I0 C3 T3 I0 C2 C2 D0 I0",
      "D3 X0* T3 C1 C3 X0 C1 S3 X0",
      "I0 I0 T2 C2 T3 I1* I0 C2 I0",
      "I1 X0 X0 D1 I1 I1 C0 X0 C3"
    ],
    "scramble": "LDLDRULUU",
    "flameSpeed": 1.6,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 5,
    "pickups": [
      {
        "x": 8,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 6,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 6,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 6,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 792900
  }
];
