// AUTO-GENERATED by scripts/generate-levels.ts - do not edit by hand.
// Regenerate with: npm run levels:generate
import type { LevelDef } from '../LevelDef';

export const GENERATED_LEVELS: LevelDef[] = [
  {
    "id": 29,
    "name": "Ember 1",
    "width": 6,
    "height": 5,
    "rows": [
      "G2 T2 C1 T1 I0 --",
      "C0 I1 I1 C2 .. D3",
      "D2 C2 C0 C0 C2 C2",
      "C1 I1 C2 D0 S0 T3",
      "C3 I0 D2 I0 C1 X0"
    ],
    "scramble": "L",
    "flameSpeed": 0.7,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 1950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 230651
  },
  {
    "id": 30,
    "name": "Kindling 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 S3 -- -- -- I1",
      "I0 D0 -- I1 I1 C3",
      "I0 G2 C1 -- -- --",
      "I0 I0 .. C3 D2 --",
      "C0 C3 -- -- X0 I1"
    ],
    "scramble": "L",
    "flameSpeed": 0.71,
    "timeLimit": 50,
    "lookahead": 3,
    "baseScore": 2000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 238570
  },
  {
    "id": 31,
    "name": "Tinder 1",
    "width": 6,
    "height": 5,
    "rows": [
      "T0 I0 -- C2 T2 --",
      "T3 .. D1 I0 C1 C1",
      "C1 C1 I1 C2 C0 D2",
      "T1 I0 X0 S0 I0 --",
      "-- G0 C0 C0 -- D2"
    ],
    "scramble": "D",
    "flameSpeed": 0.73,
    "timeLimit": 35,
    "lookahead": 3,
    "baseScore": 2050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.1,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 246489
  },
  {
    "id": 32,
    "name": "Smoulder 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 I1 I1 I1 I1 C2",
      "G0 .. I1 -- C0 I0",
      "C3 -- C1 -- -- S0",
      "C2 C0 D3 T3 -- I1",
      "C1 C1 C1 I0 I0 I1"
    ],
    "scramble": "U",
    "flameSpeed": 0.74,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.1,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 254408
  },
  {
    "id": 33,
    "name": "Flicker 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C2 S1 I1 I1 C2 T3",
      "T1 C3 C1 I1 C3 ..",
      "I1 T3 G0 C0 -- --",
      "-- I1 -- C3 C3 X0",
      "C1 I0 C0 C2 -- C0"
    ],
    "scramble": "L",
    "flameSpeed": 0.75,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 262327
  },
  {
    "id": 34,
    "name": "Spark Trail 1",
    "width": 6,
    "height": 5,
    "rows": [
      "D1 -- I1 I1 -- --",
      "S1 C2 I1 C0 I0 --",
      "C2 I0 C1 I1 G3 I1",
      "X0 C0 C3 T0 C1 I1",
      ".. D1 I0 C2 I1 X0"
    ],
    "scramble": "UR",
    "flameSpeed": 0.76,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.2,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 270246
  },
  {
    "id": 35,
    "name": "Hearth 1",
    "width": 6,
    "height": 5,
    "rows": [
      "S1 I1 I1 C2 C0 C0",
      "-- C2 X0 I0 I0 ..",
      "T3 I1 X0 C0 C2 X0",
      "I0 -- C1 T0 G0 C0",
      "C0 I1 -- C2 -- C0"
    ],
    "scramble": "LD",
    "flameSpeed": 0.78,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 278165
  },
  {
    "id": 36,
    "name": "Wick 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C1 C1 G2 T1 I0 T0",
      "-- I0 I0 -- D3 --",
      "S2 -- I0 C1 X0 I1",
      "I0 C0 I0 T1 X0 I1",
      "C0 I1 C3 X0 .. I1"
    ],
    "scramble": "LL",
    "flameSpeed": 0.79,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 286084
  },
  {
    "id": 37,
    "name": "Brazier 1",
    "width": 6,
    "height": 5,
    "rows": [
      "C2 G2 C2 I1 T0 D2",
      "D3 C0 I1 I1 I1 T1",
      "C0 X0 X0 C2 -- I0",
      ".. C2 I1 -- S1 C3",
      "C3 I1 I0 C0 X0 T0"
    ],
    "scramble": "UU",
    "flameSpeed": 0.8,
    "timeLimit": 50,
    "lookahead": 3,
    "baseScore": 2350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.3,
    "pickups": [
      {
        "x": 0,
        "y": 1,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 294003
  },
  {
    "id": 38,
    "name": "Lantern 1",
    "width": 6,
    "height": 5,
    "rows": [
      "D3 D2 C2 G1 I1 T1",
      "D3 X0 C0 C3 C0 I0",
      ".. T2 S1 I1 I1 C3",
      "C2 T1 C3 -- I1 T0",
      "D2 C0 C0 C3 C2 C0"
    ],
    "scramble": "UU",
    "flameSpeed": 0.81,
    "timeLimit": 50,
    "lookahead": 3,
    "baseScore": 2400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.4,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 301922
  },
  {
    "id": 39,
    "name": "Furnace 1",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 W11 I1 G3 C2 S1 C2",
      "-- T3 D2 T2 C2 .. I0",
      "D2 D0 D3 C0 X0 C3 I0",
      "C3 X0 C0 I0 D1 C0 W01",
      "C2 C1 -- I0 -- X0 --"
    ],
    "scramble": "DR",
    "flameSpeed": 0.83,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.4,
    "pickups": [],
    "tags": [
      "generated"
    ],
    "seed": 309841
  },
  {
    "id": 40,
    "name": "Cinder 1",
    "width": 7,
    "height": 5,
    "rows": [
      "I1 -- T0 I1 C2 I0 X0",
      "T1 C1 C0 G3 I0 I0 D2",
      "-- T0 C1 C0 S0 D1 --",
      "X0 .. -- -- X0 D1 C1",
      "X0 C2 D2 T3 I0 C1 I1"
    ],
    "scramble": "RD",
    "flameSpeed": 0.84,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 2,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 317760
  },
  {
    "id": 41,
    "name": "Ashfall 1",
    "width": 7,
    "height": 5,
    "rows": [
      "T2 C2 T1 I0 I0 D2 S2",
      "C2 D0 G2 -- D2 W11 C3",
      "I0 C3 I0 I1 .. T2 I1",
      "X0 -- I0 C1 C0 I1 --",
      "-- X0 C0 W31 C2 I1 C3"
    ],
    "scramble": "LL",
    "flameSpeed": 0.85,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 325679
  },
  {
    "id": 42,
    "name": "Blaze 1",
    "width": 7,
    "height": 5,
    "rows": [
      "D2 T3 I1 I0 C2 C3 --",
      "-- -- D0 C3 C0 I1 --",
      "-- C3 C3 C2 S1 I1 C2",
      "I1 X0 .. C2 C1 G3 I0",
      "-- D1 -- I0 C0 I1 C3"
    ],
    "scramble": "RR",
    "flameSpeed": 0.86,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.5,
    "pickups": [
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 333598
  },
  {
    "id": 43,
    "name": "Wildfire 1",
    "width": 7,
    "height": 5,
    "rows": [
      "W21 X0 .. D0 X0 I1 --",
      "I0 C2 T2 I1 W21 X0 G2",
      "I0 X0 C3 X0 C0 I1 C3",
      "I0 I1 C2 C1 C0 D0 X0",
      "S0 X0 I0 D0 C3 -- C2"
    ],
    "scramble": "LLD",
    "flameSpeed": 0.88,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.6,
    "pickups": [
      {
        "x": 0,
        "y": 1,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 341517
  },
  {
    "id": 44,
    "name": "Inferno 1",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 C3 C1 C2 I1 C1 C0",
      "T1 W11 C2 .. -- -- --",
      "-- S2 C0 C2 -- I1 X0",
      "I1 I0 D0 G0 C1 D0 I1",
      "T2 W01 D3 -- -- -- C0"
    ],
    "scramble": "DLD",
    "flameSpeed": 0.89,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 2700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.6,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 349436
  },
  {
    "id": 45,
    "name": "Torchlight 1",
    "width": 7,
    "height": 5,
    "rows": [
      "-- C2 T1 X0 I0 T0 S2",
      "I1 C0 C2 D2 C0 I1 C3",
      ".. I0 X0 C1 C2 I1 --",
      "C3 C1 D0 I0 I0 -- I1",
      "I1 -- T1 G0 X0 I1 I1"
    ],
    "scramble": "RRR",
    "flameSpeed": 0.9,
    "timeLimit": 50,
    "lookahead": 3,
    "baseScore": 2750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.7,
    "pickups": [
      {
        "x": 3,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 357355
  },
  {
    "id": 46,
    "name": "Pyre 1",
    "width": 7,
    "height": 5,
    "rows": [
      "W11 I1 C2 I0 C1 X0 T1",
      "I1 I0 I0 W01 I1 C0 I0",
      "-- -- I0 C3 C0 C1 C2",
      "X0 C1 G0 .. I1 X0 T2",
      "I0 S1 I1 C2 -- D2 C0"
    ],
    "scramble": "ULU",
    "flameSpeed": 0.92,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.7,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 365274
  },
  {
    "id": 47,
    "name": "Backdraft 1",
    "width": 7,
    "height": 5,
    "rows": [
      "-- D0 C0 C3 X0 -- C3",
      "I1 X0 I0 X0 C3 I0 C2",
      "-- D3 C0 T3 G2 X0 X0",
      "W11 I1 I1 S3 I0 .. C2",
      "D0 W11 I1 I1 C3 T2 C2"
    ],
    "scramble": "DLL",
    "flameSpeed": 0.93,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 373193
  },
  {
    "id": 48,
    "name": "Flashover 1",
    "width": 7,
    "height": 5,
    "rows": [
      "D0 C1 I0 I0 I0 -- --",
      "T3 -- I0 X0 I0 I0 I1",
      "-- -- I0 X0 W01 C3 C1",
      "X0 G1 C3 D2 -- X0 ..",
      "X0 W11 C2 C0 S2 C3 T3"
    ],
    "scramble": "ULL",
    "flameSpeed": 0.94,
    "timeLimit": 45,
    "lookahead": 3,
    "baseScore": 2900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 381112
  },
  {
    "id": 49,
    "name": "Scorch 1",
    "width": 7,
    "height": 5,
    "rows": [
      "C0 D2 D0 C3 C3 I1 T1",
      "-- T0 T1 I1 D3 C0 T3",
      "G1 C3 I0 T1 .. I0 C1",
      "C2 C1 C3 -- I1 X0 C1",
      "C3 S0 I0 T1 C3 T2 C2"
    ],
    "scramble": "UUL",
    "flameSpeed": 0.95,
    "timeLimit": 55,
    "lookahead": 3,
    "baseScore": 2950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.8,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 0,
        "kind": "ember"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 1,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 389031
  },
  {
    "id": 50,
    "name": "Sear 1",
    "width": 7,
    "height": 5,
    "rows": [
      "C1 S3 X0 I1 T2 D2 T0",
      "I0 I0 -- I0 -- -- W21",
      "I0 I1 C0 X0 I0 G1 C3",
      "C0 X0 W31 -- I1 D1 I1",
      "C3 I1 T3 D0 .. C3 D0"
    ],
    "scramble": "LUL",
    "flameSpeed": 0.97,
    "timeLimit": 40,
    "lookahead": 3,
    "baseScore": 3000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.9,
    "pickups": [
      {
        "x": 0,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 396950
  },
  {
    "id": 51,
    "name": "Char 1",
    "width": 7,
    "height": 6,
    "rows": [
      "T1 C2 D3 I1 C1 I1 D1",
      "D3 I1 G1 I1 I1 T1 I1",
      "D2 S1 I1 I1 I1 C3 I1",
      "-- -- T1 C3 C3 -- C3",
      "D2 I0 C0 I0 -- C2 --",
      "X0 C0 -- I1 -- .. --"
    ],
    "scramble": "UUU",
    "flameSpeed": 0.98,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 2.9,
    "pickups": [
      {
        "x": 0,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 404869
  },
  {
    "id": 52,
    "name": "Smoke Signal 1",
    "width": 7,
    "height": 6,
    "rows": [
      "C0 C2 C0 -- C2 X0 --",
      "C3 I0 C3 D1 X0 I1 T0",
      "I0 G0 -- I1 C3 W21 D1",
      "W11 C2 I0 -- I1 I0 T1",
      "C2 S0 -- T3 .. C0 I1",
      "I0 C2 X0 I0 X0 C0 --"
    ],
    "scramble": "DRRU",
    "flameSpeed": 0.99,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 412788
  },
  {
    "id": 53,
    "name": "Firebreak 1",
    "width": 7,
    "height": 6,
    "rows": [
      "I1 C1 W31 C0 C3 -- C1",
      "C0 I0 I0 C0 C1 W31 C3",
      "C0 I0 -- X0 S0 D0 --",
      "T0 I0 C3 T3 D0 T0 I0",
      "C3 C0 I1 C2 C1 I0 T3",
      "I1 D2 G1 C3 C2 I0 .."
    ],
    "scramble": "LLLU",
    "flameSpeed": 1,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3,
    "pickups": [
      {
        "x": 1,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 420707
  },
  {
    "id": 54,
    "name": "Flare 1",
    "width": 7,
    "height": 6,
    "rows": [
      "C0 T0 G1 I1 C3 X0 --",
      "I0 X0 C3 C2 S2 I1 --",
      "X0 C3 D3 W32 I0 C3 X0",
      "C3 I1 I1 I0 W01 W22 C1",
      "X0 C2 .. -- C1 W31 --",
      "D3 I1 -- C2 T2 -- T0"
    ],
    "scramble": "RDRR",
    "flameSpeed": 1.02,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 428626
  },
  {
    "id": 55,
    "name": "Combustion 1",
    "width": 7,
    "height": 6,
    "rows": [
      "I1 D3 C2 W21 C0 I1 T1",
      "X0 C2 C3 C0 I1 S3 W01",
      "I1 W32 I1 D2 C0 D2 C2",
      ".. -- I0 C3 C1 C1 C2",
      "I1 W02 -- G1 T1 I1 D3",
      "C0 -- C2 -- I0 -- T3"
    ],
    "scramble": "UURU",
    "flameSpeed": 1.03,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 3250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 436545
  },
  {
    "id": 56,
    "name": "Ignition 1",
    "width": 7,
    "height": 6,
    "rows": [
      "-- T3 C2 T3 C1 W31 D3",
      "C1 I1 I1 X0 C3 I1 --",
      "G0 -- I0 D3 .. C1 T1",
      "I0 D0 -- T3 W22 W22 D1",
      "C0 T3 C3 S1 C2 W21 D0",
      "X0 C0 D1 I1 C0 C3 X0"
    ],
    "scramble": "LULL",
    "flameSpeed": 1.04,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.1,
    "pickups": [
      {
        "x": 2,
        "y": 5,
        "kind": "ember"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 444464
  },
  {
    "id": 57,
    "name": "Heatwave 1",
    "width": 7,
    "height": 6,
    "rows": [
      "I1 C1 W31 W22 I1 C1 D0",
      "S1 C3 I0 C3 -- T1 I0",
      "D1 W02 X0 D3 I1 I1 T0",
      "I1 G2 -- C3 C1 C0 C3",
      "W21 C0 C2 I1 C3 -- ..",
      "C0 I1 C3 X0* I1 X0 I0"
    ],
    "scramble": "LLLL",
    "flameSpeed": 1.05,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.2,
    "pickups": [
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 452383
  },
  {
    "id": 58,
    "name": "Afterglow 1",
    "width": 7,
    "height": 6,
    "rows": [
      "T3 C1 I1 C2 I0 I0 --",
      "C3 W01 T3 C0 T2 I1 X0",
      "W22 S2 D2 I1 D0 .. C3",
      "I0 C0 I1 I1 W31 -- C1",
      "C2 -- I0 C2 C2 D2 T1",
      "W22 X0 X0 T0 G2 T2 --"
    ],
    "scramble": "LDDR",
    "flameSpeed": 1.07,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 3400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.2,
    "pickups": [
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 460302
  },
  {
    "id": 59,
    "name": "Ember 2",
    "width": 7,
    "height": 6,
    "rows": [
      "-- I0 T2 D3 C2 D0 D3",
      "C1 I1 W21 C1 C0* I0 X0",
      "D2 D0 I0 I0 I1 C1 W12",
      "I1 .. I0 G2 T2 C1 W32",
      "D1 I1 T3 C3 D2 T3 I1",
      "S1 I1 T3 W31 C0 C1 X0"
    ],
    "scramble": "RDRD",
    "flameSpeed": 1.08,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.3,
    "pickups": [
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 468221
  },
  {
    "id": 60,
    "name": "Kindling 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C3 I0 C0 I1 -- C2 C1",
      "I0 C2 D3 W21 D2 W11 C3",
      ".. X0 X0 I0 X0 T2 I0",
      "X0 W22 T1 I0 C2 W02 D0",
      "T1 I1 D3 I0 X0 C2 G1",
      "I0 T2 X0 S0 D1 -- T0"
    ],
    "scramble": "UURD",
    "flameSpeed": 1.09,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 3500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.3,
    "pickups": [
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 476140
  },
  {
    "id": 61,
    "name": "Tinder 2",
    "width": 7,
    "height": 6,
    "rows": [
      "C0 T0 C1 C2 I0 C0 ..",
      "C3 I0 X0 G0 C2 T0 D2*",
      "T2 C2 I0 C2 I0 W12 C0",
      "-- -- I0 T2 D1 S1 C2",
      "D2 X0 W01 I0 W02 W11 C3",
      "C1 X0 I0 X0 -- X0 D3"
    ],
    "scramble": "LLLLD",
    "flameSpeed": 1.11,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 3550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 484059
  },
  {
    "id": 62,
    "name": "Smoulder 2",
    "width": 7,
    "height": 6,
    "rows": [
      "-- C0 W12 I0 I0 X0 I0",
      "-- D3 T2 T1 I1 C2 D0",
      "-- -- C3 I0 I0 -- C3",
      ".. S1 I1 C2 W21 C1 G3",
      "C2 -- X0 I0 C0 C3 W21",
      "I1 I0 W32 C0 I1 T1 T2"
    ],
    "scramble": "DRRRR",
    "flameSpeed": 1.12,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 3600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 6,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 491978
  },
  {
    "id": 63,
    "name": "Flicker 2",
    "width": 7,
    "height": 6,
    "rows": [
      "-- I0 C1 I0 S2 X0 C0",
      "I0 X0 C3 I0 C0 I1 W31",
      "X0 D2 .. I0 C0 -- C2",
      "W12 I0 T3 I0 W32 C1 D3",
      "I0 T0 W31 G0 C2 -- --",
      "I0 C0 X0 C2 -- -- C0"
    ],
    "scramble": "DRRRU",
    "flameSpeed": 1.13,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 3650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.4,
    "pickups": [
      {
        "x": 1,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 499897
  },
  {
    "id": 64,
    "name": "Spark Trail 2",
    "width": 8,
    "height": 6,
    "rows": [
      "-- C2 I1 W32 I0 C0 C3 --",
      "T0 I0 D0 C3 D0 C0 T1 ..",
      "I1 C0 W12 I0 -- I1 -- C3",
      "C0 -- G1 I1 C2 I1 D3 C1*",
      "C1 I1 W31 C3 I0 S1 C2 I1*",
      "T3 I1 I1 I1 T2 W11 C3 D1"
    ],
    "scramble": "DLDLL",
    "flameSpeed": 1.14,
    "timeLimit": 70,
    "lookahead": 2,
    "baseScore": 3700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 507816
  },
  {
    "id": 65,
    "name": "Hearth 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 T1 -- -- -- D2 I1 T3",
      "W11 W32 W33 G1 I1 W32 D2 D1",
      "C0* C2 T3 C2 -- I0 D0 C1",
      "D3 I1 W11 I1 I1 I1 T1 I1",
      "C2 D3 C2 C2 T0 W23 I0 I0",
      "I0 C0 -- T2 I0 .. S0 D0"
    ],
    "scramble": "UUUUL",
    "flameSpeed": 1.16,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 3750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.5,
    "pickups": [
      {
        "x": 0,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 515735
  },
  {
    "id": 66,
    "name": "Wick 2",
    "width": 8,
    "height": 6,
    "rows": [
      "W22 G1 C2 I1 D3 X0 .. I1",
      "C0 I1 C3 C0 C0 D3 D1 I1",
      "C0 T2 W12 W31 C1 C3 -- C2",
      "C1 C0 I1 D0 W33 T3 C0 C1",
      "W21 -- W33 I1 -- D2 C3 C0",
      "C3 T3 I1 C2 -- T1 S1 I1"
    ],
    "scramble": "LDDLL",
    "flameSpeed": 1.17,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 3800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 2,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 7,
        "y": 1,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 523654
  },
  {
    "id": 67,
    "name": "Brazier 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C0 D2 D2 C2 -- X0 W13 W22",
      "T0 I1 -- I0 C3 C0 W11 T2",
      "D3 C2 .. C2 C2 I0 W03 I0",
      "I0 W21 -- G1 T1 I1 D3 D0",
      "D1 C0 C2 D3 T2 X0 C2 C3",
      "D2 S1 C3 D2 W02 T1 D2 --"
    ],
    "scramble": "LDDLU",
    "flameSpeed": 1.18,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 3850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 531573
  },
  {
    "id": 68,
    "name": "Lantern 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I0 T0* X0 I0 T2 I1 T3 --",
      "D1 .. I1 D0 I1 W03 T2 --",
      "--* D0 T2 I1 D2 T3 C1 W13",
      "S1 C2 I1* C1 I1 I1 G3 D2",
      "W22 W01 I0 T0 T0 D3 I0 W21",
      "C0 T1 I1 C3 C2 C3 X0 W02"
    ],
    "scramble": "DRRDR",
    "flameSpeed": 1.19,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 3900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.6,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 539492
  },
  {
    "id": 69,
    "name": "Furnace 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C1 C2 .. -- T3 I0 I0 I0",
      "T2 S0 -- C2 W32 D0 C1 --",
      "T3 C2 W21 T0 C3 X0 D1 I1",
      "I1 C0 C3 T2 -- I1 T3 D1",
      "D2 C3 I0 C1 T2 G2 W02 C1",
      "I0 C2 D0 W11 I1 T2 -- C0"
    ],
    "scramble": "DRULDD",
    "flameSpeed": 1.21,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 3950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.7,
    "pickups": [
      {
        "x": 5,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "ember"
      },
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 547411
  },
  {
    "id": 70,
    "name": "Cinder 2",
    "width": 8,
    "height": 6,
    "rows": [
      "W21 D1 C0 X0 X0 G3 X0* C3",
      "X0 -- C0 -- C0 T3 T3 C2",
      "I0 C1 I1 D0 X0 C2 -- W33",
      "S0 I1 I0 X0 X0 C0 W11 W32",
      "X0 D3 W22 I0 -- C0 W23 C1",
      "-- I0 I0 C1 .. C3* C1 D2"
    ],
    "scramble": "URRRUL",
    "flameSpeed": 1.22,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 4000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.7,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "ember"
      },
      {
        "x": 2,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 0,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 555330
  },
  {
    "id": 71,
    "name": "Ashfall 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I0 X0 I0 C0 S2 D3 -- T2",
      "C2 .. I0 T1 C0 C2 -- W01",
      "T0 W13 C1 T3 C1 I0 C0 I1",
      "D3 C3 C2 C3 W33 I0 C0 D3",
      "-- G1 I1 I1 C2 W01 T3 C2",
      "W12 I1 I1 I1 C3 D0 -- W22"
    ],
    "scramble": "DDRRDD",
    "flameSpeed": 1.23,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.8,
    "pickups": [
      {
        "x": 7,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 563249
  },
  {
    "id": 72,
    "name": "Blaze 2",
    "width": 8,
    "height": 6,
    "rows": [
      "-- C2 C2 D3 W21 C1* -- X0",
      "T0 I1 D1 C1 C0 I1 S3 I1",
      ".. C1 D2 C1 W23 I1 C3 T0",
      "T1 C1 I0 C2 W22 W03 T0 D3",
      "X0 W22 C1 C2 X0 C2 X0 I0",
      "I1 W01 G0 C0 C3 I1* -- --"
    ],
    "scramble": "DDRULD",
    "flameSpeed": 1.25,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.8,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 571168
  },
  {
    "id": 73,
    "name": "Wildfire 2",
    "width": 8,
    "height": 6,
    "rows": [
      "-- C2 X0 I0 C3 X0 C0 C0",
      "-- T3 X0 D0 -- I1 C2 W03",
      "T1* C0* W21 -- -- W03 I1 D2",
      "D1 I1 T3 I1 W32 S2 X0 C1",
      "C1* C0 .. C1 C2 I0 C1 --",
      "C2 C0 W12 T2 G0 C0 W31 X0"
    ],
    "scramble": "DRURUU",
    "flameSpeed": 1.26,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 0,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 579087
  },
  {
    "id": 74,
    "name": "Inferno 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 --* -- D1 D3 I0 T1 C3",
      "W33 -- C1* C0 W33 D3 C1 G3",
      "C1 D3 X0 X0 T2 D1 I0 I0",
      "W32 I0 I0 I0 C0* C3 C0 I1",
      "I0 D3 C1 C3* W12 C2 W21 --*",
      "S1 I1 W31 .. C0 C0 C3 I1"
    ],
    "scramble": "RURDRR",
    "flameSpeed": 1.27,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 587006
  },
  {
    "id": 75,
    "name": "Torchlight 2",
    "width": 8,
    "height": 6,
    "rows": [
      "X0 -- W21 I0 G0 C3 S1 C2",
      "X0 C3 W02 D0 C0 T1 W11 C3",
      "C3 D2 X0 I1 I1 C1 C1 C1",
      "C1 W32 D0 -- X0 C0 T3 W03",
      "I0 W03 C3 C1 C2 C1 .. C2",
      "T3 T3 I1 T2 I0 C0 D1 I1"
    ],
    "scramble": "DRUUUL",
    "flameSpeed": 1.28,
    "timeLimit": 70,
    "lookahead": 2,
    "baseScore": 4250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 3.9,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 594925
  },
  {
    "id": 76,
    "name": "Pyre 2",
    "width": 8,
    "height": 6,
    "rows": [
      "W03 I0 W12 I1 C2 .. -- X0",
      "I1 C0 C2 C1 C3 I0 C1* D1",
      "X0 I0 W01 I0 C3 C1 -- W21",
      "I1 C1 G3 I0 -- D0 -- W02",
      "I0 C0 I1 C3 C0 C1 C1 --",
      "-- S2 C2 W13 X0 X0 T3 C2"
    ],
    "scramble": "DDDRUR",
    "flameSpeed": 1.3,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 602844
  },
  {
    "id": 77,
    "name": "Backdraft 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 D2 D0 I0 -- I1 C1 C2",
      "W03 I0 W33 I0 S2 C1 I0 W01",
      "T3 C1 W32 I0 C0 I1 T2 I1",
      "D2 T0 C3 W02 -- C1 I0 D1",
      "I1 G0 I1 W21 -- -- D0 ..",
      "C0 I0 C0 I0 T2 -- T0 D2"
    ],
    "scramble": "ULURDL",
    "flameSpeed": 1.31,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 4350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 610763
  },
  {
    "id": 78,
    "name": "Flashover 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C3 W02 D3 D0* C0 --* T2 I1",
      "I1 C1 T3 I1 I1 I1 C2 --",
      "X0* I0 D2 X0 X0 C0 I0 I1",
      "I1 S0 T1 I0 D1 I1 C0 W31",
      "C3 C2 C1 .. I0 W32 C1 I0",
      "W11 I1 G3 C2 T3 I0 X0 I1"
    ],
    "scramble": "URRUURU",
    "flameSpeed": 1.32,
    "timeLimit": 45,
    "lookahead": 2,
    "baseScore": 4400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.1,
    "pickups": [
      {
        "x": 2,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "ember"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 618682
  },
  {
    "id": 79,
    "name": "Scorch 2",
    "width": 8,
    "height": 6,
    "rows": [
      "-- D1 I1 C0 I1 C2 C3 X0",
      "C3 W11 T1 I1 S3 I0 .. T3",
      "I1 -- C1 C1 W03 I0 C1 C3*",
      "-- I1 I1 W22 T1 G0 I1* D2",
      "W11 C2 C1 T2 W13 X0 C3 C2",
      "W12 C3 I0 I0 C3 I1* -- --"
    ],
    "scramble": "LDLDDLU",
    "flameSpeed": 1.33,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.1,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 626601
  },
  {
    "id": 80,
    "name": "Sear 2",
    "width": 8,
    "height": 6,
    "rows": [
      "D1* -- -- T0 -- -- X0 T0",
      "I1 W22 D2 -- D3 C1 C3 --",
      "C0 X0 D0 -- C0 C1 X0 X0",
      "W11 C3 C1 C0 W33 C2 -- W21",
      "C1 X0 C2 C3 W23 C0 S1 C3",
      "W02 G1 C3 -- C2 D3 C0 .."
    ],
    "scramble": "LLLLLUU",
    "flameSpeed": 1.35,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 4500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 0,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 634520
  },
  {
    "id": 81,
    "name": "Char 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C2 C1 -- C1 W32 W23 G2 W11",
      "S0 I0 W03 I0 X0 C1 I0 T0",
      "W11 I1 W32 I0 I1 D3 I0 X0",
      "I1 C1 X0 C0 I1 I1 C3 C0",
      "T2 C2 T2 D2 T0 -- I0 ..",
      "-- C0 T1 I0 I1* T3 D0 T0"
    ],
    "scramble": "DLULUUR",
    "flameSpeed": 1.36,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4550,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 3,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "ember"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 642439
  },
  {
    "id": 82,
    "name": "Smoke Signal 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 D3 W21 -- .. C0 W12 T1",
      "C0 C1 C0 X0 I1 S3 W11 C3",
      "C1 T2 G1 T1 I1 D3 C0 I0",
      "C0 X0 T1 C0 C2 C2 W33 D0",
      "X0* I1 T2 C0 I0 -- -- D2",
      "C0 C3* I0 W33 W02 C2 D0 C2"
    ],
    "scramble": "LLDLURR",
    "flameSpeed": 1.37,
    "timeLimit": 65,
    "lookahead": 2,
    "baseScore": 4600,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.2,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 0,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 650358
  },
  {
    "id": 83,
    "name": "Firebreak 2",
    "width": 8,
    "height": 6,
    "rows": [
      "D2 T0 I1 W32 I1 .. C2 T2",
      "I0 T2 W33 -- T0 T0 I0 I0",
      "I0 I0 C2 C3 C0 --* -- W01",
      "C1 C3 -- T0 C0 W33 W11 C2",
      "C0 G3 I0 -- -- X0 D2 W02",
      "C1 D2 X0 S1 I1 T1 I1 C2"
    ],
    "scramble": "DRRULLL",
    "flameSpeed": 1.38,
    "timeLimit": 60,
    "lookahead": 2,
    "baseScore": 4650,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.3,
    "pickups": [
      {
        "x": 0,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 5,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 658277
  },
  {
    "id": 84,
    "name": "Flare 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 X0 I0* W11 I1 I1 W32 C3",
      "T1 C3 D0 T3* D2 -- D0 C0*",
      "C0 W03 -- C1 I0 I0 -- T3",
      "T3 T2 W33 G2 I0 I0 S2 X0",
      "T2 W12 I1 C3 T0 I1 C3 C2",
      ".. C2 I0 W11 C3 C3 I1 C2"
    ],
    "scramble": "RRRURUR",
    "flameSpeed": 1.4,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4700,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.3,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 4,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 666196
  },
  {
    "id": 85,
    "name": "Combustion 2",
    "width": 8,
    "height": 6,
    "rows": [
      "I1 C2 C0 I1 I1 I1 S3 W12",
      "G1 C3 C1 C2 X0 D1 C1 W03",
      "C0 X0 I0 I0 C3 C1 T2* T2",
      "C2 C3 I0 W01 I1 I1 T3* W22",
      "I1 I0 T2 C0 -- C1* C0 X0",
      "I1 .. I0 T0 W33 I1 I1 W01"
    ],
    "scramble": "LUUURUR",
    "flameSpeed": 1.41,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4750,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.4,
    "pickups": [
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 674115
  },
  {
    "id": 86,
    "name": "Ignition 2",
    "width": 8,
    "height": 6,
    "rows": [
      "W13 I0 -- X0 X0 I0 C1* I0",
      "-- S0 C1 C3 T0 T0 C2* D0",
      ".. I0 T1* W12 I1 I1 C2 W22",
      "C1 I0 W23 D0 G1 I1 C3 I0",
      "D1 -- D0 T2 C2 C0 W11 C3",
      "C1 W21 T3 I1* -- -- -- I0"
    ],
    "scramble": "RDRDRUU",
    "flameSpeed": 1.42,
    "timeLimit": 40,
    "lookahead": 2,
    "baseScore": 4800,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.4,
    "pickups": [
      {
        "x": 7,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 5,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 682034
  },
  {
    "id": 87,
    "name": "Heatwave 2",
    "width": 8,
    "height": 6,
    "rows": [
      "X0 -- C2 C1 X0 W02 C2 --",
      "I1 I1 D3 C2* I0 D3 G1 T1",
      "-- X0 T1 X0 C1 W32 -- X0",
      "I1 T2 C1 I1 W31 C2 .. I0",
      "D3 D0 X0 -- C3 S2 C3 W01",
      "I0 X0 C0 I1 T1 C3 I0 D1"
    ],
    "scramble": "LLLDLURD",
    "flameSpeed": 1.44,
    "timeLimit": 55,
    "lookahead": 2,
    "baseScore": 4850,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 0,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 689953
  },
  {
    "id": 88,
    "name": "Afterglow 2",
    "width": 8,
    "height": 6,
    "rows": [
      "C3 D0 I0 S0 I1 X0 -- X0",
      "-- C1* -- D2 W12 I1 W31 W23",
      "I0 C3 W21 C2* T1 D3 T3 W03",
      "T2 .. C0 C2 C1 I1 C2 D3",
      "C1 C0 I0 T2 W02 C1 C3 C0",
      "C0 I1 C3 I0 G1 C3 X0 --"
    ],
    "scramble": "RRRDRDRU",
    "flameSpeed": 1.45,
    "timeLimit": 50,
    "lookahead": 2,
    "baseScore": 4900,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 6,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 697872
  },
  {
    "id": 89,
    "name": "Ember 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C1 I0 .. W02 C0* C0 I1* -- C2",
      "G2 I0 --* C1 W13 I1 T2 -- I1",
      "C0 I1 I1 C2 D3 C1 I1 W31 T2",
      "-- T2* C1 I0 T1 I0 C0 I1 C0",
      "-- I1 D1 C0 C2 S0 I1 W22 I1",
      "T3 C1 W23 -- I0 T1 T3 W01 I0",
      "C1* C1 X0 C1 C3 T3 --* C1 C0"
    ],
    "scramble": "LDDRDRUR",
    "flameSpeed": 1.46,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 4950,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.5,
    "pickups": [
      {
        "x": 4,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 6,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 3,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 705791
  },
  {
    "id": 90,
    "name": "Kindling 3",
    "width": 9,
    "height": 7,
    "rows": [
      "T1 I0 -- W22 C0 X0 C1 I1 W31",
      "T0 -- C0* I0 D1 I1 T3 W32 --",
      "I1 S2 W33 I0 X0* X0 I0 C2 ..",
      "-- I0 -- T0 -- -- C0 D2 W23",
      "C2 W01 C0 I0 D0 -- D2 C1 T2*",
      "C3 C1 G2 I0 C1 X0 I0 C0 C2",
      "-- X0 C0 C3 I1 C1 I0 I0 C0"
    ],
    "scramble": "DLLDLUUU",
    "flameSpeed": 1.47,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5000,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.6,
    "pickups": [
      {
        "x": 4,
        "y": 1,
        "kind": "ember"
      },
      {
        "x": 5,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 713710
  },
  {
    "id": 91,
    "name": "Tinder 3",
    "width": 9,
    "height": 7,
    "rows": [
      "I0 I1 T2 C0 I1 W31 S2 -- --",
      "X0 X0 I0* C1 -- I1 I0 I0 --*",
      "X0 I1 I1 I1 I1 C2 I0 C1 I1",
      "I1 C0 D0 -- W21 G0 I0 W02 T3",
      "W13 T0 T1 C0 C0 I1 C3 T2 T2",
      "-- D3 C0 C0 W03 C1 I1 -- T1",
      ".. -- C2 W22 -- X0 D3 -- D1"
    ],
    "scramble": "RRRULDRR",
    "flameSpeed": 1.49,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5050,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.6,
    "pickups": [
      {
        "x": 7,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 721629
  },
  {
    "id": 92,
    "name": "Smoulder 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C2 I1 I1 D3 -- T1 S1 C2 C1",
      "W02 X0 C1 T0 I1 T1 W23 I0 I0",
      "C1 T0 -- D3 -- C0 I1 W01 T2",
      "X0 C3 I1 I1 --* C2 G1 C2 T2",
      "T0 -- C3 .. X0 -- W22 C0 C3",
      "W23 X0 -- T2* I1 X0 X0 I1 D2",
      "C1 -- W11 I1 X0 I1 C3 C3 I0"
    ],
    "scramble": "RRUUURDR",
    "flameSpeed": 1.5,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5100,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 1,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 0,
        "kind": "ember"
      },
      {
        "x": 8,
        "y": 3,
        "kind": "oil"
      },
      {
        "x": 8,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 8,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 729548
  },
  {
    "id": 93,
    "name": "Flicker 3",
    "width": 9,
    "height": 7,
    "rows": [
      "W21 C2 -- I1 D0* -- -- C0 T3*",
      "T0 W22 D1 X0* C1 T2* D3 T2 --",
      "T2 I0 -- -- -- I0 I1 T3 I1",
      "C3 I0 T0 X0 C0 W13 T3 I1 S1",
      "C1 C3 W13 I1 T2 I1 W21 I0 I1",
      "I0 I1 C1 D1 I1 I1 C0 I1 W32",
      "C0 G3 -- .. I0 -- D1 I1 I1"
    ],
    "scramble": "URRRUULD",
    "flameSpeed": 1.51,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5150,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 3,
        "y": 5,
        "kind": "ember"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 5,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 5,
        "kind": "wood"
      },
      {
        "x": 6,
        "y": 6,
        "kind": "ember"
      },
      {
        "x": 7,
        "y": 6,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 737467
  },
  {
    "id": 94,
    "name": "Spark Trail 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C0 W01 C1* I1 I0 C0 T3 W23 --*",
      "T3* I0 D2 W13 I0 W22 .. I1 I1",
      "C3 T2 I0 C3 D0 X0 T1 T1 C3",
      "-- C0* I0 W22 -- T0 -- I1* C0",
      "-- S2 T0 C3 X0 W01 -- C0 I1",
      "C1 I0 X0 -- C1 G3 T2 T0 I1",
      "C1 I0 C0 T1 C3 C1 C0 X0 I1"
    ],
    "scramble": "DLULURDD",
    "flameSpeed": 1.52,
    "timeLimit": 60,
    "lookahead": 1,
    "baseScore": 5200,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.7,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 2,
        "kind": "ember"
      },
      {
        "x": 2,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 4,
        "y": 5,
        "kind": "oil"
      },
      {
        "x": 4,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 745386
  },
  {
    "id": 95,
    "name": "Hearth 3",
    "width": 9,
    "height": 7,
    "rows": [
      "W33 -- I0 I0 C0 C2 -- D2 I0",
      "I1 .. C1 T3 I1 C2 T3 C2 S0",
      "W32 C0* I0 C2 C2 I0 C0 C1 W11",
      "I0 C3 T2 X0 -- I0 T0 -- D2",
      "C0 W13 W02 -- -- G0 T2 I1 W21",
      "T1 -- --* I0 I1 C2* I0 -- I0",
      "I1 D2 X0 I1* C3* -- I0 X0 I0"
    ],
    "scramble": "LDDRRRRU",
    "flameSpeed": 1.54,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5250,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.8,
    "pickups": [
      {
        "x": 5,
        "y": 2,
        "kind": "oil"
      },
      {
        "x": 8,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 753305
  },
  {
    "id": 96,
    "name": "Wick 3",
    "width": 9,
    "height": 7,
    "rows": [
      "W33 D2 W02 C0 T1 C2 -- W01 I1",
      "I0 C1 I0 G1 X0 C3 C1 D2 I1",
      "I1 I0 -- I1 C1 C1 X0 W31 --",
      "X0 C3 I1 -- I0 S0 D3 -- --",
      "W13 .. I0 I0 I0 I1 I1 C2 X0",
      "I0 --* C3 D2 C2 -- I1 C1 W32",
      "C0 D1 C1 C2 C2 -- I0 T2 X0*"
    ],
    "scramble": "LDDRRRRRR",
    "flameSpeed": 1.55,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5300,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.8,
    "pickups": [
      {
        "x": 4,
        "y": 1,
        "kind": "wood"
      },
      {
        "x": 7,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 761224
  },
  {
    "id": 97,
    "name": "Brazier 3",
    "width": 9,
    "height": 7,
    "rows": [
      "C0 T3 X0 T1 T3 I1 I1 W32 X0",
      "T0 D2 D0 C3 D0 C3 I0 C3 T0",
      "T1 I0 -- I0* C3 C1 -- X0 C1",
      "C3 I0 I0 -- W22 C2 I0* .. D2",
      "I0 C1 C2 D3 W01 W13 C0 C1 --",
      "D1 G0 I0 T1 X0 S1 C2 -- I0",
      "C1 I1 C3 C2 -- C0 W01 W23 X0"
    ],
    "scramble": "RULURULDD",
    "flameSpeed": 1.56,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 5350,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.9,
    "pickups": [
      {
        "x": 4,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 1,
        "kind": "oil"
      },
      {
        "x": 1,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 1,
        "y": 3,
        "kind": "wood"
      },
      {
        "x": 2,
        "y": 4,
        "kind": "oil"
      },
      {
        "x": 3,
        "y": 4,
        "kind": "ember"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 769143
  },
  {
    "id": 98,
    "name": "Lantern 3",
    "width": 9,
    "height": 7,
    "rows": [
      "D3 X0 C3 D1 X0 C1 C3 I1 W33",
      "I0* -- -- X0 X0 -- D0 X0 D3",
      "T1 I1 I1 C2 W22 I0 I0 I1 C1",
      "I1 --* T2 X0 I0 I1 C0* C2 I0",
      "D3 C3 -- G0 X0 W21 -- W23 I0",
      "-- C1* S2 T2 I0 I0 D0 X0 W02",
      "-- .. C0 W31 C0 C3 -- -- --"
    ],
    "scramble": "LUUUURUUL",
    "flameSpeed": 1.57,
    "timeLimit": 55,
    "lookahead": 1,
    "baseScore": 5400,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 4.9,
    "pickups": [
      {
        "x": 1,
        "y": 2,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 4,
        "kind": "oil"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 777062
  },
  {
    "id": 99,
    "name": "Furnace 3",
    "width": 9,
    "height": 7,
    "rows": [
      "I0 D0 C3* .. I0 T3 D1 C0 C2",
      "C1* C1 C3 -- C0 C2 --* --* C0*",
      "I0 W23 C3 C1 C1 S3 C1* I1 C1",
      "W22 C3* W11 I1 C3 W22 C2 I0 X0",
      "I0 D0 T1 C1 I1 C3 C2 D3 X0",
      "C3 C0 W03 W01 C1 I1 T3 I1 I1",
      "T1 I1 -- I1* G0 C3 C3 D3* C0"
    ],
    "scramble": "RDLLDDDRU",
    "flameSpeed": 1.59,
    "timeLimit": 50,
    "lookahead": 1,
    "baseScore": 5450,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 5,
    "pickups": [
      {
        "x": 3,
        "y": 4,
        "kind": "wood"
      },
      {
        "x": 0,
        "y": 5,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 784981
  },
  {
    "id": 100,
    "name": "Cinder 3",
    "width": 9,
    "height": 7,
    "rows": [
      "D3 W11 W32 -- X0 C1 I1 I1 C3",
      "D2 C0 C3 C1 X0 I0 D0* C2 G2",
      "W03 X0* C1 C1 I1 I0 C3 T2 I0",
      "C2 W03 T1 D2 C2* W02 -- T0 I0",
      "C2 C2 X0 D2 C2 -- C1 S3 I0",
      "C0 C2 X0 C2 C3 T2 W01 D1 X0",
      "I0 -- C2 C2 C2 .. C0* I0 T2"
    ],
    "scramble": "LUURUUUUR",
    "flameSpeed": 1.6,
    "timeLimit": 45,
    "lookahead": 1,
    "baseScore": 5500,
    "initialFuel": 100,
    "maxFuel": 100,
    "fuelPerTile": 5,
    "pickups": [
      {
        "x": 7,
        "y": 0,
        "kind": "wood"
      },
      {
        "x": 8,
        "y": 6,
        "kind": "wood"
      }
    ],
    "tags": [
      "generated"
    ],
    "seed": 792900
  }
];
