/**
 * Generates levels FIRST_GENERATED_LEVEL..100 deterministically and bakes them
 * into src/level/data/generated.ts so the game ships with static level data.
 *
 *   npm run levels:generate
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateLevel } from '../src/puzzle/Generator';
import { gridToRows } from '../src/level/LevelParser';
import { difficultyFor, FIRST_GENERATED_LEVEL, LAST_LEVEL } from '../src/level/difficulty';
import type { LevelDef } from '../src/level/LevelDef';

const NAMES = [
  'Ember', 'Kindling', 'Tinder', 'Smoulder', 'Flicker', 'Spark Trail', 'Hearth', 'Wick', 'Brazier', 'Lantern',
  'Furnace', 'Cinder', 'Ashfall', 'Blaze', 'Wildfire', 'Inferno', 'Torchlight', 'Pyre', 'Backdraft', 'Flashover',
  'Scorch', 'Sear', 'Char', 'Smoke Signal', 'Firebreak', 'Flare', 'Combustion', 'Ignition', 'Heatwave', 'Afterglow',
];

const levels: LevelDef[] = [];
for (let id = FIRST_GENERATED_LEVEL; id <= LAST_LEVEL; id++) {
  const prof = difficultyFor(id);
  let seed = 1000 + id * 7919;
  let generated = null;
  for (let tries = 0; tries < 50 && !generated; tries++) {
    try {
      generated = generateLevel({ width: prof.width, height: prof.height, difficulty: prof.difficulty, seed, flameSpeed: prof.flameSpeed });
    } catch {
      seed += 1;
    }
  }
  if (!generated) throw new Error(`Failed to generate level ${id}`);
  const traversal = generated.routeLength / generated.flameSpeed;
  const timeLimit = Math.max(25, Math.ceil((traversal * 3 + 12) / 5) * 5);
  const n = id - FIRST_GENERATED_LEVEL;
  const name = `${NAMES[n % NAMES.length]} ${Math.floor(n / NAMES.length) + 1}`;
  levels.push({
    id,
    name,
    width: prof.width,
    height: prof.height,
    rows: gridToRows(generated.solvedGrid),
    scramble: generated.scramble,
    flameSpeed: generated.flameSpeed,
    timeLimit,
    lookahead: prof.lookahead,
    baseScore: prof.baseScore,
    initialFuel: generated.initialFuel,
    maxFuel: generated.maxFuel,
    fuelPerTile: generated.fuelPerTile,
    pickups: generated.pickups,
    tags: ['generated'],
    seed: generated.seed,
  });
  console.log(
    `level ${id}: ${prof.width}x${prof.height} speed ${generated.flameSpeed} route ${generated.routeLength} (main ${generated.mainPathLength}, detours ${generated.detours}) ` +
      `scramble ${generated.scramble} pickups ${generated.pickups.length} fuel/tile ${generated.fuelPerTile} seed ${generated.seed}`,
  );
}

const header = `// AUTO-GENERATED by scripts/generate-levels.ts - do not edit by hand.\n// Regenerate with: npm run levels:generate\nimport type { LevelDef } from '../LevelDef';\n\nexport const GENERATED_LEVELS: LevelDef[] = `;
writeFileSync(resolve('src/level/data/generated.ts'), `${header}${JSON.stringify(levels, null, 2)};\n`);
console.log(`wrote ${levels.length} levels`);
